package GlitchVape::Effect::Overlay;

use strict;
use warnings;
use utf8;

use Encode ();

use GlitchVape::Chicago   ();
use GlitchVape::Magick    ();
use GlitchVape::Pixels    ();
use GlitchVape::Raster    ();
use GlitchVape::Starfield ();
use GlitchVape::VGA       ();
use GlitchVape::Registry  ();
use GlitchVape::Fonts     ();
use GlitchVape::Palette   ();

our $VERSION = '0.01';

=head1 NAME

GlitchVape::Effect::Overlay - text, camcorder furniture and drawn graphics

=head1 DESCRIPTION

Everything drawn on top of the picture rather than done to it. These run last,
because on-screen display is generated by the camera or the player and is not
subject to the tape damage the picture went through -- which is exactly why
crisp white C<REC> text over a degraded image reads as authentic.

=cut

my $R  = 'GlitchVape::Registry';
my $PI = 3.14159265358979;

# Stock phrases. Mostly the words the genre actually uses, which are not always
# the words a translation would pick: 蒸気波 is a literal calque of "vapor
# wave" that exists because of the genre, not before it.
my @PHRASES = (
    'ヴェイパーウェイブ',    # vaporwave
    '蒸気波',          # vapor wave (calque)
    '美的',           # aesthetic
    '未来',           # future
    '夢',            # dream
    '無限',           # infinity
    '電脳',           # cyber
    '東京',           # Tokyo
    '音楽',           # music
    '現実を超えて',       # beyond reality
    '記憶',           # memory
    '孤独',           # solitude
    '夜',            # night
    '水',            # water
    '新世紀',          # new century
);

# ---------------------------------------------------------------------------

$R->register(
    name    => 'text',
    title   => 'Text',
    stage   => 'overlay',
    summary => 'Draw text over the image',
    doc     => <<'DOC',
Renders a phrase, picked at random from a built-in list of Japanese ones
unless C<invent> is turned off and one is typed into C<string>. Across a loop
C<reroll> says whether the choice is remade every frame -- which is the
default, and is what makes the text flicker -- or held for the whole render.

An empty C<string> with C<invent> off draws nothing, which is how to have the
effect in a pipeline and silent for one render.

The C<shadow> offset draws the same text in a contrasting colour behind the
main copy, which is what stops light text disappearing into a light
background.
DOC
    params => {
        string => {
            order       => 10,
            label       => 'Phrase',
            placeholder => 'Nothing drawn',
            default     => '',
            type        => 'str',
            needs       => { invent => 0 },
            doc         => 'Text to draw; empty draws nothing',
        },

        # These two are ordered and the rest of the effect is not, which is
        # the whole of what the ordering is for here: a switch that decides
        # whether the box above it means anything has to be beside it, and no
        # spelling of 'string' and 'invent' puts them together alphabetically.
        invent => {
            order   => 20,
            label   => 'Random phrase',
            default => 1,
            type    => 'bool',
            doc     => 'Pick a phrase from the built-in list instead of '
                . 'drawing the one above',
        },
        reroll => {
            label     => 'Varying phrase',
            default   => 1,
            type      => 'bool',
            animation => 1,
            needs     => { invent => 1 },
            doc       => 'Pick again on every frame, which is what makes the '
                . 'text flicker; off holds one phrase for the whole loop',
        },
        font => {
            default => 'cjk',
            type    => 'str',
            doc     => 'Font role (cjk, vcr, pixel, mono, sans) or a font path',
        },
        size => {
            default => 12,
            type    => 'num',
            min     => 0.5,
            max     => 100,
            doc     => 'Height of the type as a percentage of the image height',
        },
        gravity => {
            default => 'Center',
            type    => 'enum',
            values  => [
                qw(NorthWest North NorthEast West Center East
                    SouthWest South SouthEast)
            ],
            doc => 'Where the text sits',
        },
        color => {
            default => '#FFFFFF',
            type    => 'str',
            doc     => 'Fill colour',
        },
        shadow => {
            default => '#FF00AA',
            type    => 'str',
            doc     => 'Offset copy drawn behind; empty to disable',
        },
        shadow_offset => {
            default => 4,
            type    => 'num',
            min     => -100,
            max     =>  100,
            doc     => 'Shadow displacement in pixels',
        },
        opacity => {
            default => 0.9,
            type    => 'num',
            min     => 0,
            max     => 1,
            doc     => 'Text opacity',
        },
        x => {
            default => 0.04,
            type    => 'num',
            min     => -1,
            max     =>  1,
            doc     => 'Horizontal inset as a fraction of width',
        },
        y => {
            default => 0.04,
            type    => 'num',
            min     => -1,
            max     =>  1,
            doc     => 'Vertical inset as a fraction of height',
        },
        rotate => {
            default => 0,
            type    => 'num',
            min     => -180,
            max     =>  180,
            doc     => 'Rotation in degrees',
        },
        spacing => {
            default => 0,
            type    => 'num',
            min     => -50,
            max     => 200,
            doc     => 'Extra letter spacing; wide tracking is a genre staple',
        },
    },
    apply => \&_text,
);

sub _text
{
    my ( $ctx, $p ) = @_;
    return if $p->{ opacity } <= 0;

    # A phrase from the list, or the one that was typed. It used to be that an
    # empty string meant "surprise me", which made the difference between a
    # picked phrase and a typed one invisible in the interface -- the box was
    # there to be typed into whether or not anything typed into it would be
    # drawn. The switch says it instead, and an empty box now means the one
    # plain thing it looks like.
    my $str = $p->{ string };

    if ( $p->{ invent } )
    {
        # rng_fixed is the same stream on every frame of the loop, so the
        # phrase holds; rng_for folds the frame index in, so it does not.
        my $rng =
              $p->{ reroll }
            ? $ctx->rng_for( 'text' )
            : $ctx->rng_fixed( 'text' );

        $str = $rng->pick( @PHRASES );
    }

    return unless length $str;

    # Wide tracking is done by hand because ImageMagick has no letter-spacing
    # control; inserting thin spaces is the usual workaround.
    if ( $p->{ spacing } > 0 )
    {
        my $gap = ' ' x ( int( $p->{ spacing } / 8 ) || 1 );
        $str = join $gap, split //, $str;
    }

    my ( $w, $h ) = $ctx->dims;
    my $font =
        GlitchVape::Fonts::resolve_or_die( $p->{ font }, "effect 'text'" );
    my $size = int( $h * $p->{ size } / 100 ) || 8;

    my $dx = int( $w * $p->{ x } );
    my $dy = int( $h * $p->{ y } );

    my %common = (
        string  => $str,
        font    => $font,
        size    => $size,
        gravity => $p->{ gravity },
        opacity => $p->{ opacity },
        rotate  => $p->{ rotate },
    );

    if ( length $p->{ shadow } && $p->{ shadow_offset } )
    {
        _annotate(
            $ctx, %common,
            color => $p->{ shadow },
            x     => $dx + $p->{ shadow_offset },
            y     => $dy + $p->{ shadow_offset },
        );
    }

    _annotate( $ctx, %common, color => $p->{ color }, x => $dx, y => $dy );
    return;
}

# ---------------------------------------------------------------------------

$R->register(
    name    => 'osd',
    title   => 'Camcorder OSD',
    stage   => 'overlay',
    summary => 'Camcorder on-screen display: REC, timestamp, tape mode',
    doc     => <<'DOC',
The furniture a 1990s camcorder burned into the picture. Defaults place a
blinking record indicator top-left and a date/time bottom-right, which is where
most consumer models actually put them.

The timestamp is invented by default -- a real present-day date on a vaporwave
image is an anachronism that undercuts the whole effect. Turn `invent` off and
`date` and `time` are drawn exactly as they are typed; either of them left
empty is simply not drawn, which is how to have a time and no date.
DOC
    params => {
        color => {
            order   => 10,
            label   => 'Colour',
            default => '#FFFFFF',
            type    => 'str',
            doc     => 'Text colour',
        },
        font => {
            order   => 20,
            label   => 'Font',
            default => 'vcr',
            type    => 'str',
            doc     => 'Font role or path',
        },
        size => {
            order   => 30,
            label   => 'Text size',
            default => 4.5,
            type    => 'num',
            min     => 0.5,

            # It was 50, which is an SP that fills half the frame -- and a
            # slider whose every usable value sat in its first tenth. This is
            # camcorder furniture, so it has a size: roughly the 4.5% below,
            # and 12 is already taller than anything a deck ever burned in.
            # The caption effects keep their 100, because oversized type is
            # the point of a caption and not of an OSD.
            max => 12,
            doc => 'Height of the type as a percentage of the image height',
        },
        margin => {
            order   => 40,
            label   => 'Margin',
            default => 0.045,
            type    => 'num',
            min     => 0,
            max     => 0.5,
            doc     => 'Inset from the edges',
        },
        timestamp => {
            order   => 50,
            label   => 'Timestamp',
            default => 1,
            type    => 'bool',
            doc     => 'Draw the date and time',
        },
        invent => {
            order   => 60,
            label   => 'Invent timestamp',
            default => 1,
            type    => 'bool',
            needs   => { timestamp => 1 },
            doc     => 'Make up a 1990s date and time from the seed, '
                . 'ignoring the two fields below',
        },
        date => {
            order       => 70,
            label       => 'Date',
            placeholder => 'Not shown',
            default     => 'JUN 15 1995',
            type        => 'str',
            needs       => { timestamp => 1, invent => 0 },
            doc         => 'Date as it should read; empty draws no date',
        },
        time => {
            order       => 80,
            label       => 'Time',
            placeholder => 'Not shown',
            default     => 'PM  3:47',
            type        => 'str',
            needs       => { timestamp => 1, invent => 0 },
            doc         => 'Time as it should read; empty draws no time',
        },
        camera => {
            order   => 90,
            label   => 'Camera mode',
            default => 'REC',
            type    => 'str',
            suggest => [ 'REC', 'PLAY', 'PLAY-FF' ],
            doc     => 'Transport indicator, top left; empty draws none',
        },
        rec_mode => {
            order   => 100,
            label   => 'DV REC mode',
            default => 'SP',
            type    => 'str',
            suggest => [ qw(SP LP HD) ],
            doc     => 'Tape speed, top right; empty to omit',
        },
        reroll => {
            order     => 110,
            label     => 'Varying timestamp',
            default   => 0,
            type      => 'bool',
            animation => 1,
            needs     => { timestamp => 1, invent => 1 },
            doc       => 'Invent a new timestamp on every frame, so the '
                . 'clock cannot settle on a date',
        },
        blink => {
            order     => 120,
            label     => 'Icon blink',
            default   => 1,
            type      => 'bool',
            animation => 1,
            needs     => { camera => 1 },
            doc       => 'Flash the camera indicator across the loop',
        },
    },
    apply => \&_osd,
);

# What a camera mode draws beside its label. A known transport state has a
# glyph the hardware drew; anything typed in is text alone, because a glyph
# guessed from an unrecognised word would be inventing a claim about what the
# deck is doing.
my %CAMERA_GLYPH = (
    'REC'     => 'dot',
    'PLAY'    => 'play',
    'PLAY-FF' => 'ff',
);

sub _osd
{
    my ( $ctx, $p ) = @_;

    my ( $w, $h ) = $ctx->dims;

    # Which stream the invented date comes out of is the whole of `reroll`.
    #
    # rng_fixed is the same numbers on every frame, and is the default because
    # a camcorder's clock is a fact about when the tape was made: it does not
    # change within two seconds of footage, and one that did read as a bug.
    #
    # rng_for folds the frame index in, so the display cannot settle on a date
    # at all. That was what this did by accident, and it turns out to be worth
    # keeping: a timestamp riffling through a decade is a picture of not
    # remembering when something happened, which is a thing several of these
    # presets are about. It is an answer to a different question, so it is a
    # setting rather than the default.
    my $rng =
          $p->{ reroll }
        ? $ctx->rng_for( 'osd' )
        : $ctx->rng_fixed( 'osd' );
    my $font =
        GlitchVape::Fonts::resolve_or_die( $p->{ font }, "effect 'osd'" );
    my $size = int( $h * $p->{ size } / 100 ) || 10;

    # Every piece of on-screen display shares its face, size and colour; only
    # the string and corner change.
    my %osd = ( font => $font, size => $size, color => $p->{ color } );

    # Where the corners are, kept beside the type it has to line up with:
    # three numbers that every piece of the display needs and none of them
    # varies, which is one argument rather than three at each call.
    my $box = {
        mx   => int( $w * $p->{ margin } ),
        my   => int( $h * $p->{ margin } ),
        size => $size,
        osd  => \%osd,
    };

    _osd_camera( $ctx, $p, $box );
    _osd_timestamp( $ctx, $p, $box, $rng );

    if ( length $p->{ rec_mode } )
    {
        _annotate(
            $ctx, %osd,
            string  => $p->{ rec_mode },
            gravity => 'NorthEast',
            x       => $box->{ mx },
            y       => $box->{ my },
        );
    }
    return;
}

# One indicator, not one per transport state. rec and play were separate
# switches with a separate label each, which made "REC and PLAY at once" a
# reachable setting -- a deck is in one transport state, and offering the
# other thing was offering a picture no camcorder ever showed.
sub _osd_camera
{
    my ( $ctx, $p, $box ) = @_;

    my ( $mx, $my, $size ) = @{ $box }{ qw(mx my size) };

    my $mode = $p->{ camera };
    return unless length $mode;

    # The whole indicator blinks, glyph and label together, which is what a
    # camcorder in standby actually does -- and what makes the setting mean
    # something for a mode typed in by hand, which has no glyph to flash.
    if ( $ctx->frames > 1 && $p->{ blink } && $ctx->phase >= 0.6 )
    {
        return;
    }

    my $glyph = $CAMERA_GLYPH{ uc $mode };
    my $x     = $mx;

    if ( $glyph )
    {
        _osd_glyph( $ctx, $p, $glyph, $box );

        # Past whatever was drawn, which is wider for the two triangles of a
        # fast wind than for the one of a play.
        $x = $mx + int( $size * ( $glyph eq 'ff' ? 1.4 : 0.95 ) );
    }

    _annotate(
        $ctx, %{ $box->{ osd } },
        string  => $mode,
        gravity => 'NorthWest',
        x       => $x,
        y       => $my,
    );

    return;
}

sub _osd_glyph
{
    my ( $ctx, $p, $glyph, $box ) = @_;

    my ( $mx, $my, $size ) = @{ $box }{ qw(mx my size) };

    my $r  = int( $size * 0.32 );
    my $cy = $my + int( $size * 0.42 );

    if ( $glyph eq 'dot' )
    {
        # Red whatever the text colour is: the record lamp was a red LED, and
        # a white one reads as a full stop.
        my $cx = $mx + $r;
        $ctx->magick( '-fill', '#FF2020', '-stroke', 'none', '-draw',
            sprintf( 'circle %d,%d %d,%d', $cx, $cy, $cx + $r, $cy ),
        );
        return;
    }

    my $tri = int( $size * 0.45 );
    my $top = $cy - $tri;

    # Two triangles for a fast wind, one for play -- the same shorthand as the
    # buttons on the deck, so the picture reads without the label.
    my @x = ( $mx );
    push @x, $mx + int( $tri * 1.05 ) if $glyph eq 'ff';

    for my $x0 ( @x )
    {
        $ctx->magick(
            '-fill',
            $p->{ color },
            '-stroke',
            'none', '-draw',
            sprintf(
                'polygon %d,%d %d,%d %d,%d',
                $x0,             $top,             $x0,
                $top + $tri * 2, $x0 + $tri * 1.7, $top + $tri
            ),
        );
    }

    return;
}

sub _osd_timestamp
{
    my ( $ctx, $p, $box, $rng ) = @_;

    my ( $mx, $my, $size ) = @{ $box }{ qw(mx my size) };

    return unless $p->{ timestamp };

    # Invented or literal, never a mixture. It used to be that an empty field
    # meant "invent this one", which made the difference between a made-up
    # date and a typed one invisible in the interface and impossible to state
    # in --explain: the switch says it instead, and an empty field now means
    # the one plain thing it looks like it means.
    my ( $date, $time ) = ( $p->{ date }, $p->{ time } );
    if ( $p->{ invent } )
    {
        $date = _fake_date( $rng );
        $time = _fake_time( $rng );
    }

    if ( length $time )
    {
        _annotate(
            $ctx, %{ $box->{ osd } },
            string  => $time,
            gravity => 'SouthEast',
            x       => $mx,
            y       => $my,
        );
    }

    if ( length $date )
    {
        _annotate(
            $ctx, %{ $box->{ osd } },
            string  => $date,
            gravity => 'SouthEast',
            x       => $mx,
            y       => $my + int( $size * 1.25 ),
        );
    }

    return;
}

my @MONTH = qw(JAN FEB MAR APR MAY JUN JUL AUG SEP OCT NOV DEC);

sub _fake_date
{
    my ( $rng ) = @_;
    return sprintf '%s %02d %d',
        $rng->pick( @MONTH ),
        $rng->int_between( 1,    28 ),
        $rng->int_between( 1990, 1999 );
}

sub _fake_time
{
    my ( $rng ) = @_;

    # 12-hour with a leading space, the way the cheap OSD chips rendered it.
    my $meridiem = 'PM';
    if ( $rng->chance( 0.5 ) )
    {
        $meridiem = 'AM';
    }

    return sprintf '%s %2d:%02d',
        $meridiem,
        $rng->int_between( 1, 12 ),
        $rng->int_between( 0, 59 );
}

# ---------------------------------------------------------------------------

$R->register(
    name    => 'grid',
    title   => 'Perspective Grid',
    stage   => 'overlay',
    summary => 'Retro perspective grid and sun',
    doc     => <<'DOC',
The synthwave horizon: a ground plane receding to a vanishing point, optionally
with a banded sun sitting on it. Horizontal line spacing follows a power curve
so the lines bunch up towards the horizon the way perspective actually makes
them, rather than being evenly spaced.
DOC
    params => {
        horizon => {
            default => 0.62,
            type    => 'num',
            min     => 0.05,
            max     => 0.95,
            doc     => 'Horizon height as a fraction from the top',
        },
        lines_h => {
            default => 14,
            type    => 'int',
            min     => 0,
            max     => 200,
            doc     => 'Number of horizontal lines',
        },
        lines_v => {
            default => 22,
            type    => 'int',
            min     => 0,
            max     => 200,
            doc     => 'Number of converging vertical lines',
        },
        color => {
            default => '#FF00AA',
            type    => 'str',
            doc     => 'Grid line colour',
        },
        width => {
            default => 2,
            type    => 'num',
            min     => 0.2,
            max     => 20,
            doc     => 'Line width in pixels',
        },
        opacity => {
            default => 0.75,
            type    => 'num',
            min     => 0,
            max     => 1,
            doc     => 'Grid opacity',
        },
        perspective => {
            default => 2.2,
            type    => 'num',
            min     => 1,
            max     => 8,
            doc => 'How hard the horizontal lines bunch towards the horizon',
        },
        drift => {
            animation => 1,
            default   => 0,
            type      => 'num',
            min       => -64,
            max       =>  64,
            doc       => 'Grid lines travelled per loop; negative recedes',
        },
        sun => {
            default => 1,
            type    => 'bool',
            doc     => 'Draw the banded sun',
        },
        sun_size => {
            default => 0.22,
            type    => 'num',
            min     => 0.02,
            max     => 1,
            doc     => 'Sun diameter as a fraction of image width',
        },
        sun_colors => {
            default => '#FFE261,#FF3864',
            type    => 'str',
            doc     => 'Top and bottom colours of the sun gradient',
        },
        sun_bands => {
            default => 7,
            type    => 'int',
            min     => 0,
            max     => 60,
            doc     => 'Slots cut across the lower half of the sun',
        },
    },
    apply => \&_grid,
);

sub _grid
{
    my ( $ctx, $p ) = @_;
    return if $p->{ opacity } <= 0;
    require Image::Magick;

    my ( $w, $h ) = $ctx->dims;
    my $hy = int( $h * $p->{ horizon } );
    my $cx = int( $w / 2 );

    my $layer = Image::Magick->new( size => "${w}x${h}" );
    GlitchVape::Magick::check( $layer->Read( 'xc:transparent' ),
        "grid: could not create layer" );

    _draw_sun( $layer, $p, $w, $h ) if $p->{ sun };

    my @draw;

    # Horizontal lines: t^perspective spaces them tightly at the horizon and
    # widely at the bottom of the frame.
    #
    # Drift moves them along that curve rather than down the screen, which is
    # the whole trick: a line travelling at constant speed in t accelerates
    # towards the viewer exactly as the spacing widens, so the plane reads as
    # ground going past instead of as stripes sliding. One line spacing is the
    # repeat, so travel() snaps to whole lines and the loop closes with a line
    # sitting where its neighbour started.
    #
    # Only these move. The vertical lines converge on the vanishing point and
    # are the same set of rays whatever the ground is doing; scrolling them
    # would swing the whole plane sideways.
    my $shift = $ctx->travel( $p->{ drift }, 1 );
    my $extra = int( abs $p->{ drift } ) + 1;

    for my $i ( 1 - $extra .. $p->{ lines_h } + $extra )
    {
        my $t = ( $i + $shift ) / $p->{ lines_h };

        # Off the top past the horizon, or off the bottom of the frame.
        next if $t <= 0 || $t > 1;

        my $y = $hy + ( $h - $hy ) * ( $t**$p->{ perspective } );
        push @draw, sprintf( 'line 0,%.1f %d,%.1f', $y, $w, $y );
    }

    # Vertical lines all converge on the vanishing point. Spreading their
    # bottom ends well past the frame edges keeps the outermost ones steep
    # enough to look like part of the same plane.
    if ( $p->{ lines_v } )
    {
        my $spread = $w * 2.5;
        for my $i ( 0 .. $p->{ lines_v } )
        {
            my $t = $i / $p->{ lines_v };
            my $x = $cx - $spread / 2 + $spread * $t;
            push @draw, sprintf( 'line %d,%d %.1f,%d', $cx, $hy, $x, $h );
        }
    }

    if ( @draw )
    {
        for my $d ( @draw )
        {
            my ( $prim, @pts ) = split ' ', $d;
            $layer->Draw(
                primitive   => $prim,
                points      => join( ' ', @pts ),
                stroke      => $p->{ color },
                strokewidth => $p->{ width },
                fill        => 'none',
                antialias   => 'true',
            );
        }
    }

    if ( $p->{ opacity } < 1 )
    {
        $layer->Evaluate(
            operator => 'Multiply',
            value    => $p->{ opacity },
            channel  => 'Alpha',
        );
    }

    $ctx->image->Composite( image => $layer->[ 0 ], compose => 'Over' );
    return;
}

sub _draw_sun
{
    my ( $layer, $p, $w, $h ) = @_;
    require Image::Magick;

    # Horizon and centre are derived rather than passed in: they are a
    # function of the geometry the caller already hands over.
    my $hy = int( $h * $p->{ horizon } );
    my $cx = int( $w / 2 );

    my $d = int( $w * $p->{ sun_size } );
    return if $d < 4;
    my $r = int( $d / 2 );

    my @cols = split /\s*,\s*/, $p->{ sun_colors };
    push @cols, $cols[ 0 ] if @cols < 2;

    # Build the sun as its own square image: a vertical gradient masked by a
    # circle. Drawing a gradient-filled circle directly is not something
    # ImageMagick's draw primitives can do.
    my $disc = Image::Magick->new( size => "${d}x${d}" );
    $disc->Read( "gradient:$cols[0]-$cols[1]" );

    my $mask = Image::Magick->new( size => "${d}x${d}" );
    $mask->Read( 'xc:black' );
    $mask->Draw(
        primitive => 'circle',
        points    => sprintf( '%d,%d %d,%d', $r, $r, $r, 0 ),
        fill      => 'white',
        stroke    => 'none',
    );

    # Slots across the lower half, widening towards the bottom.
    if ( $p->{ sun_bands } )
    {
        for my $i ( 1 .. $p->{ sun_bands } )
        {
            my $t  = $i / ( $p->{ sun_bands } + 1 );
            my $y  = $r + ( $d - $r ) * ( $t**1.4 );
            my $th = 1 + $t * $r * 0.16;
            $mask->Draw(
                primitive   => 'line',
                points      => sprintf( '0,%.1f %d,%.1f', $y, $d, $y ),
                stroke      => 'black',
                strokewidth => $th,
                fill        => 'none',
            );
        }
    }

    # The mask carries the shape as black and white pixels, so its intensity
    # has to be moved into its alpha channel before the composite. IM6's
    # CopyOpacity fell back to intensity when the source had no alpha; IM7
    # aliases CopyOpacity to CopyAlpha, which copies the alpha channel and
    # nothing else -- and `xc:black` arrives with a fully opaque one. Without
    # the copy the sun composites as an opaque square with no slots in it.
    $mask->Set( alpha => 'copy' );

    $disc->Set( alpha => 'on' );
    $disc->Composite( image => $mask->[ 0 ], compose => 'CopyAlpha' );

    my $x = $cx - $r;
    my $y = $hy - int( $r * 1.15 );

    $layer->Composite(
        image   => $disc->[ 0 ],
        compose => 'Over',
        x       => $x,
        y       => $y
    );
    return;
}

# ---------------------------------------------------------------------------

$R->register(
    name    => 'letterbox',
    title   => 'Letterbox & Border',
    stage   => 'framing',
    summary => 'Black bars, or a border around the frame',
    doc     => <<'DOC',
Crops to a target aspect ratio with bars, or draws a plain inset border. Bars
sell the "recorded off a broadcast" idea; a border reads more like a photo
print.

C<ratio> is a closed list, because an aspect ratio is one of a short set of
shapes film and television were shot in and a typed one is a typo waiting to
fail the render. C<native> is on it for the case the presets actually use:
three of the four that letterbox want the border and nothing else.

C<pattern> fills the bars and the border with one of the eight-by-eight
patterns a desktop of the period offered, in C<color> over C<ink>, instead of
a flat colour. They are bitmaps rather than drawings, scaled by pixel
replication -- see L<GlitchVape::Raster/desktop_names() / desktop_tile( $dir,
%opt )>.

With a pattern the ground is built once and the picture laid on it, rather
than the canvas being extended twice. That is not tidiness: a pattern has to
line up across the join between the bars and the border, and extending twice
restarts it at the second one.

C<swap> is the animation. The two pattern colours cross over the loop and come
back, on one cosine, so it closes by construction and it is slow: once out and
once home for the whole loop is a breath rather than a strobe. A full swap
passes through the moment the two are equal and the pattern is briefly not
there, which is what a full swap is; below about a half they only lean towards
each other and it breathes without ever going.
DOC
    params => {
        ratio => {
            default => 'native',
            type    => 'str',
            order   => 1,

            # Closed rather than typeable: an aspect ratio is one of a short
            # list of shapes film and television were shot in, and a typed
            # one is a typo waiting to fail the render.
            choose => 'ratio',
            doc    => 'Shape to crop the frame to. Native leaves it as it is '
                . 'and draws only the border',
        },
        border => {

            # Not nought any more. The ratio now arrives at 'native', which
            # is what three of the four presets that letterbox actually want,
            # and 'native' with no border is an effect that does nothing when
            # it is switched on.
            default => 0.03,
            type    => 'num',
            min     => 0,
            max     => 0.5,
            order   => 2,
            doc     => 'Uniform border as a fraction of the shorter side',
        },
        color => {
            default => 'black',
            type    => 'str',
            order   => 3,
            doc     => 'Bar or border colour, and the ground a pattern is '
                . 'drawn on',
        },
        pattern => {
            default => 'solid',
            type    => 'enum',
            order   => 4,
            values  => [ 'solid', GlitchVape::Raster::desktop_names() ],
            doc     => 'Fill the bars and the border with one of the '
                . 'eight-by-eight patterns a desktop of the period offered, '
                . 'instead of a flat colour',
        },
        ink => {
            default => '#FF71CE',
            type    => 'str',
            order   => 5,
            doc     => "The pattern's marks, over the colour above. Unused "
                . 'while the pattern is solid',
        },
        swap => {
            animation => 1,
            default   => 0,
            type      => 'num',
            min       => 0,
            max       => 1,
            order     => 7,
            doc       => 'How far the two pattern colours cross over the '
                . 'loop and back. Once out and once home, so a loop is one '
                . 'slow breath rather than a flicker',
        },
        pattern_scale => {
            default => 0,
            type    => 'int',
            min     => 0,
            max     => 16,
            order   => 6,
            doc     => 'Image pixels per pattern pixel; 0 works it out from '
                . 'the picture, on the reading that it is a screen 480 '
                . 'pixels tall',
        },
    },
    apply => \&_letterbox,
);

# The two numbers in '16:9'.
sub _ratio_of
{
    my ( $ratio ) = @_;

    my ( $rw, $rh ) =
        $ratio =~ m{^\s*(\d+(?:\.\d+)?)\s*[:x/]\s*(\d+(?:\.\d+)?)\s*$}
        or die "letterbox: ratio must look like '16:9', got '$ratio'\n";

    return ( $rw, $rh );
}

# The tile the bars and the border are filled with, or undef for a flat
# colour -- which keeps the plain case on the two ImageMagick calls it has
# always used, and renders identically to before.
sub _letterbox_tile
{
    my ( $ctx, $p ) = @_;

    my $name = $p->{ pattern } // 'solid';
    return undef if $name eq 'solid';

    my ( undef, $h ) = $ctx->dims;

    # The same reading chicago's zoom takes: the picture is a screen 480
    # pixels tall, and a pattern pixel is however many image pixels that
    # makes. An eight-pixel tile at 1:1 on a twelve-megapixel photograph is a
    # texture nobody can see.
    my $scale = int( $p->{ pattern_scale } || 0 ) || _chicago_zoom( $h );

    my ( $ground, $ink ) = _swapping( $ctx, $p );

    return GlitchVape::Raster::desktop_tile(
        $ctx->cachedir,
        name   => $name,
        ground => $ground,
        ink    => $ink,
        scale  => $scale,
    );
}

# The two pattern colours at this point in the loop.
#
# One cosine over the whole loop, so it goes out and comes home once and
# closes by construction -- and slowly, which is the point: a pattern that
# swapped every few frames would be a strobe, and this is meant to be the
# thing you notice second.
#
# At a swap of 1 the colours cross completely, which means passing through the
# moment they are equal and the pattern is not there. That is a fade out and
# back inverted, and it is what a full swap is. Below about a half they only
# lean towards each other and the pattern breathes without ever going.
#
# Not quantised, unlike the cmyk screens: a tile is six milliseconds and a
# kilobyte, where a screen is a third of a second and a megabyte.
sub _swapping
{
    my ( $ctx, $p ) = @_;

    my ( $ground, $ink ) = ( $p->{ color }, $p->{ ink } );

    my $swap = $p->{ swap } || 0;
    return ( $ground, $ink ) unless $swap > 0 && $ctx->frames > 1;

    my $mix = $swap * ( 1 - cos( 2 * $PI * $ctx->phase ) ) / 2;

    return (
        GlitchVape::Raster::mixed( $ground, $ink,    $mix ),
        GlitchVape::Raster::mixed( $ink,    $ground, $mix ),
    );
}

# Bars, border, or both, filled with a tile. Built as one background the
# picture is laid on rather than as two extends, because a pattern has to line
# up across the join -- extending twice would restart it at the border.
sub _letterbox_tiled
{
    my ( $ctx, $p, $ratio, $tile ) = @_;
    require Image::Magick;

    my ( $w, $h ) = $ctx->dims;

    my ( $nw, $nh ) = ( $w, $h );

    if ( length $ratio )
    {
        my ( $rw, $rh ) = _ratio_of( $ratio );

        my $target = $rw / $rh;

        ( $nw, $nh ) =
            $w / $h > $target
            ? ( $w, int( $w / $target ) )
            : ( int( $h * $target ), $h );
    }

    # From the shorter side of what the bars left, which is what the flat
    # path does too: a panorama should not get an absurd frame on its short
    # edge.
    my $border = int( ( $nw < $nh ? $nw : $nh ) * $p->{ border } );

    $nw += 2 * $border;
    $nh += 2 * $border;

    return if $nw <= $w && $nh <= $h;

    my $ground = GlitchVape::Raster::tiled( $ctx, $tile, $nw, $nh );

    my $out = Image::Magick->new;
    GlitchVape::Magick::check( $out->Read( $ground ),
        'letterbox: could not lay the pattern down' );

    GlitchVape::Magick::check(
        $out->Composite(
            image   => $ctx->image->[ 0 ],
            compose => 'Over',
            x       => int( ( $nw - $w ) / 2 ),
            y       => int( ( $nh - $h ) / 2 ),
        ),
        'letterbox: could not place the picture on it'
    );

    $ctx->image( $out );

    return;
}

sub _letterbox
{
    my ( $ctx, $p ) = @_;

    # 'native' is the name the list offers for what an empty string has always
    # meant, because a closed list cannot offer nothing.
    my $ratio = $p->{ ratio } // q{};
    $ratio = q{} if lc $ratio eq 'native';

    my $tile = _letterbox_tile( $ctx, $p );

    if ( $tile )
    {
        return _letterbox_tiled( $ctx, $p, $ratio, $tile );
    }

    if ( length $ratio )
    {
        my ( $rw, $rh ) = _ratio_of( $ratio );

        my ( $w, $h ) = $ctx->dims;
        my $target = $rw / $rh;
        my $cur    = $w / $h;

        my ( $nw, $nh ) =
            $cur > $target
            ? ( $w, int( $w / $target ) )
            : ( int( $h * $target ), $h );

        $ctx->magick(
            '-background', $p->{ color }, '-gravity', 'Center',
            '-extent',     "${nw}x${nh}",
        );
    }

    if ( $p->{ border } > 0 )
    {
        my ( $w, $h ) = $ctx->dims;

        # Border width is a fraction of the shorter side, so a panorama does
        # not get an absurdly thick frame on its short edge.
        my $shorter = $h;
        if ( $w < $h )
        {
            $shorter = $w;
        }

        my $b = int( $shorter * $p->{ border } );
        $ctx->magick( '-bordercolor', $p->{ color }, '-border', $b ) if $b > 0;
    }
    return;
}

# ---------------------------------------------------------------------------

$R->register(
    name    => 'watermark',
    title   => 'Tiled Watermark',
    stage   => 'overlay',
    summary => 'Tiled repeating text across the whole frame',
    doc     => <<'DOC',
Repeats a string in a low-contrast grid over the image, in the manner of a
stock-photo proof or a corrupted screensaver.

C<drift> slides the whole tiling along the text's own reading direction, so
with C<rotate> set the motion comes out diagonal and the thing reads as the
screensaver it is imitating. This is the effect that animates most cleanly of
any of them, and for a reason worth knowing: a tiled pattern has an exact
period, so moving it a whole number of tiles per loop returns it to itself
with nothing to hide and no speed at which it goes wrong. Everything else that
drifts has to snap or rock to close its loop; this one simply closes.
DOC
    params => {
        string => {
            default => '美的',
            type    => 'str',
            doc     => 'Text to repeat',
        },
        font => {
            default => 'cjk',
            type    => 'str',
            doc     => 'Font role or path',
        },
        size => {
            default => 5,
            type    => 'num',
            min     => 0.5,
            max     => 100,
            doc     => 'Height of the type as a percentage of the image height',
        },
        color => {
            default => '#FFFFFF',
            type    => 'str',
            doc     => 'Text colour',
        },
        opacity => {
            default => 0.12,
            type    => 'num',
            min     => 0,
            max     => 1,
            doc     => 'Overall opacity',
        },
        rotate => {
            default => -30,
            type    => 'num',
            min     => -180,
            max     =>  180,
            doc     => 'Rotation of the tiled text',
        },
        spacing => {
            default => 2.2,
            type    => 'num',
            min     => 1,
            max     => 12,
            doc     => 'Gap between repetitions, in multiples of text size',
        },
        drift => {
            animation => 1,
            default   => 0,
            type      => 'num',
            min       => -32,
            max       =>  32,
            doc       => 'Tiles the pattern slides per loop; negative reverses',
        },
        direction => {
            animation => 1,
            default   => 'east',
            type      => 'enum',
            values    => [
                qw(north northeast east southeast
                    south southwest west northwest)
            ],
            doc => 'Compass direction the pattern slides, on the screen',
        },
    },
    apply => \&_watermark,
);

sub _watermark
{
    my ( $ctx, $p ) = @_;
    return if $p->{ opacity } <= 0;
    require Image::Magick;

    my ( $w, $h ) = $ctx->dims;
    my $font =
        GlitchVape::Fonts::resolve_or_die( $p->{ font }, "effect 'watermark'" );
    my $size = int( $h * $p->{ size } / 100 ) || 8;

    # Rotating the finished layer means building it on an oversized canvas so
    # the corners are still covered afterwards. The diagonal is the minimum
    # that can contain the frame at any angle; the margin on top covers the
    # tile that is half in shot at the edge.
    my $diag = int( sqrt( $w * $w + $h * $h ) ) + $size * 4;

    my $layer = Image::Magick->new( size => "${diag}x${diag}" );
    $layer->Read( 'xc:transparent' );

    my $text = Encode::encode( 'UTF-8', $p->{ string } );
    my $gap  = int( $size * $p->{ spacing } ) || $size;

    # How wide the string actually comes out, rather than how wide a character
    # of it is. Spacing the columns on the point size alone works only while
    # the string is about as wide as it is tall: give it a sentence and every
    # repetition is drawn across the next one, and the whole band turns into a
    # smear. Asking the font settles it for any string in any face.
    my @metrics = $layer->QueryFontMetrics(
        text      => $text,
        font      => $font,
        pointsize => $size,
        encoding  => 'UTF-8',
    );
    my $ink = $metrics[ 4 ] || $size;

    # The lattice. Horizontally a repetition plus its gap, so two of them
    # never touch; vertically two rows, because the odd ones are staggered and
    # it takes two to come back to the same offset.
    my $xperiod = int( $ink + $gap );
    my $yperiod = $gap * 2;

    my ( $sx, $sy ) = _watermark_slide( $ctx, $p, $xperiod, $yperiod );

    # Enough margin that whatever is sliding in from either side is already
    # drawn by the time it arrives.
    my $row = 0;
    for ( my $y = -$yperiod ; $y < $diag + $yperiod ; $y += $gap )
    {
        # Every other row offset by half a tile, so the tiling reads as a
        # scatter rather than as columns.
        my $stagger = $row++ % 2 ? int( $xperiod / 2 ) : 0;

        for ( my $x = -$xperiod ; $x < $diag + $xperiod ; $x += $xperiod )
        {
            $layer->Annotate(
                text      => $text,
                font      => $font,
                pointsize => $size,
                fill      => $p->{ color },
                x         => $x + $stagger + $sx,
                y         => $y + $sy,
                gravity   => 'NorthWest',
                encoding  => 'UTF-8',
                antialias => 'true',
            );
        }
    }

    $layer->Rotate( degrees => $p->{ rotate }, background => 'transparent' );

    # Before the crop, not after. Rotate leaves the layer with a virtual
    # canvas offset describing where the original sat inside the new bounds,
    # and Crop measures from that rather than from the pixels -- so the window
    # comes off the corner of the rotated square instead of its middle, and a
    # wedge of the frame ends up with no watermark on it at all. It is not a
    # small wedge: at 45 degrees it was a seventh of the picture.
    $layer->Set( page => '0x0+0+0' );

    $layer->Set( gravity => 'Center' );
    $layer->Crop( geometry => "${w}x${h}+0+0", gravity => 'Center' );
    $layer->Set( page => '0x0+0+0' );

    $layer->Evaluate(
        operator => 'Multiply',
        value    => $p->{ opacity },
        channel  => 'Alpha',
    );

    $ctx->image->Composite(
        image   => $layer->[ 0 ],
        compose => 'Over',
        gravity => 'Center',
    );
    return;
}

# Screen-space unit vectors, y downward as the raster has it.
#
# Written out rather than abbreviated, because the text effect's `gravity`
# spells its compass in full and two effects naming the same eight directions
# two different ways is a thing to remember for no reason. 'se' also has to be
# decoded every time it is read, and a preset is read far more often than it
# is written.
my %COMPASS = (
    north     => [  0, -1 ],
    northeast => [  1, -1 ],
    east      => [  1,  0 ],
    southeast => [  1,  1 ],
    south     => [  0,  1 ],
    southwest => [ -1,  1 ],
    west      => [ -1,  0 ],
    northwest => [ -1, -1 ],
);

# Where the tiling has slid to by this frame, as ( x, y ) in layer pixels.
#
# The direction is asked for on the screen, but the sliding happens on the
# layer, before it is turned by C<rotate>. So the compass vector is turned the
# other way first, and then rounded to a whole number of tiles on each axis --
# because only whole tiles bring the pattern back to itself, and a loop that
# does not come back jolts once per repeat forever.
#
# Rounding is what makes the direction approximate whenever C<rotate> is not a
# multiple of a right angle, and the approximation is better the further the
# pattern travels: one tile of drift can only be rounded to one of eight
# directions, six tiles to far more. At C<rotate> 0 nothing is approximated.
sub _watermark_slide
{
    my ( $ctx, $p, $xperiod, $yperiod ) = @_;

    my $compass = $COMPASS{ lc $p->{ direction } } or return ( 0, 0 );

    my ( $dx, $dy ) = @$compass;

    # Normalised, so a diagonal travels as fast as a cardinal rather than the
    # square root of two times faster.
    my $length = sqrt( $dx**2 + $dy**2 ) || 1;
    $dx /= $length;
    $dy /= $length;

    # Undoing the rotation the layer has not had applied yet.
    my $rad = -$p->{ rotate } * $PI / 180;
    my $lx  = $dx * cos( $rad ) - $dy * sin( $rad );
    my $ly  = $dx * sin( $rad ) + $dy * cos( $rad );

    # In tiles, then rounded to whole ones.
    my $tiles = $p->{ drift } || 0;
    my $mx    = _round( $tiles * $lx );
    my $my    = _round( $tiles * $ly * $xperiod / $yperiod );

    # Rounding both to nothing would take a drift somebody asked for and make
    # it stand still, which reads as a broken parameter. The larger component
    # gets the one tile instead.
    if ( $tiles && !$mx && !$my )
    {
        if   ( abs $lx >= abs $ly ) { $mx = $lx < 0 ? -1 : 1 }
        else                        { $my = $ly < 0 ? -1 : 1 }
    }

    my $phase = $ctx->phase;

    return (
        _wrap( $mx * $xperiod * $phase, $xperiod ),
        _wrap( $my * $yperiod * $phase, $yperiod )
    );
}

# ---------------------------------------------------------------------------

$R->register(
    name    => 'chicago',
    title   => 'Chicago Window',
    stage   => 'overlay',
    summary => 'A 1995 window frame, hollow, around the picture',
    doc     => <<'DOC',
Draws a Windows 95 window over the picture with the document area left
transparent, so the photograph is what the window is showing.

Every part of it is drawn rather than scaled from a screenshot, which is what
lets the size be a setting: a window's furniture is a fixed number of pixels
and does not grow with the window, so a wider one has the same four-pixel
border and one longer scroll bar rather than a fatter everything.
L<GlitchVape::Chicago> is where that anatomy lives.

C<theme> is the palette, and there are three: C<default>, the neutral grey
window under a navy caption that Windows arrived in, and C<rose> and C<rain>,
two of the schemes from its Appearance tab. Each of those is two colours -- a
dark that is both the caption bar and every shadowed edge, and a light that is
every face -- with the white highlight and the black dark shadow unchanged,
because a raised edge reads as raised by being brighter than anything around
it and a tinted highlight flattens the window.

C<icon> is the picture in the top left corner. It arrives as this program's
own -- the V and the A from F<assets/artwork/icon-256.png>, redrawn at sixteen
pixels rather than scaled down to them -- and C<notepad> puts back the
document page the window was scavenged from. The icon keeps its own colours
under every theme, because an application's icon did not change with the
desktop scheme.

C<jitter> is the animation setting: how far the window may jump from where it
was put, redrawn every frame, so that it shakes in place rather than sitting
there. It is measured in the window's own pixels, so the dance is the same
size on a phone photograph and on a thumbnail.

It is not called C<drift>, which everywhere else here means a pattern
travelling in a direction over the loop -- a journey, snapped by
C<Context::travel> to whole repeats so that it arrives back where it set out.
This one goes nowhere. It closes its loop all the same, by the easier route:
C<Context::rng_phase> keys the roll on the frame's position around the loop
rather than on its index, so the frame after the last one is the first one
again.

C<zoom> is how many image pixels one of the window's own pixels becomes, and
it is a whole number because the alternative is interpolation -- a soft grey
where there should be a one-pixel white highlight, which is precisely the
thing that stops a bevel reading as raised. Left at 0 it is worked out from
the picture, on the reading that the picture is a screen 480 pixels tall: a
1080-pixel photograph gets 2, a 3000-pixel one gets 6.

The caption and the menu are drawn at the window's own size and enlarged with
it, so the lettering comes out as blocky as everything else -- a crisply set
caption over four-pixel bevels would look like a caption pasted onto a
photograph of a window.

C<type_size> is that size, and twelve is what the interface itself used. It
has a floor under it that the font decides: a stem narrower than one pixel
misses the pixel centres a rasteriser samples at, and does so for some of the
positions it can land in and not others -- so at twelve pixels W95FA writes
'File' as 'Fıle' and 'Help' intact, which reads as a broken font rather than
as a size one pixel too small. Asked for less than a font can manage, the
window quietly draws it at what it can: twelve for the C<pixel> role, thirteen
for W95FA. Eighteen is as large as the caption bar will hold.
DOC
    params => {
        width => {
            default => 0.72,
            type    => 'num',
            min     => 0.1,
            max     => 1,
            order   => 1,
            doc     => "The window's width as a fraction of the picture's",
        },
        height => {
            default => 0.72,
            type    => 'num',
            min     => 0.1,
            max     => 1,
            order   => 2,
            doc     => "Its height as a fraction of the picture's",
        },
        gravity => {
            default => 'Center',
            type    => 'enum',
            order   => 3,
            values  => [
                qw(NorthWest North NorthEast West Center East
                    SouthWest South SouthEast)
            ],
            doc => 'Which part of the picture it is anchored to',
        },
        x => {
            default => 0,
            type    => 'num',
            min     => -1,
            max     =>  1,
            order   =>  4,
            doc     => 'Horizontal inset from that anchor, as a fraction '
                . 'of the width',
        },
        y => {
            default => 0,
            type    => 'num',
            min     => -1,
            max     =>  1,
            order   =>  5,
            doc     => 'Vertical inset, as a fraction of the height',
        },
        zoom => {
            default => 0,
            type    => 'int',
            min     => 0,
            max     => 12,
            order   => 6,
            doc => 'Image pixels per window pixel. 0 reads the picture as a '
                . 'screen 480 tall and rounds, so anything under 720 gets 1 '
                . 'and 0 and 1 are the same there; 1080 gets 2, 2160 gets 5',
        },
        theme => {
            default => 'default',
            type    => 'enum',
            order   => 7,
            values  => [ GlitchVape::Chicago::themes() ],
            doc     => 'Which of the schemes from the Appearance tab the '
                . 'window is painted in',
        },
        icon => {
            default => 'glitchvape',
            type    => 'enum',
            order   => 8,
            values  => [ GlitchVape::Chicago::icons() ],
            doc     => 'The picture in the top left: this program, or the '
                . 'document page the window was scavenged from',
        },
        title => {
            default     => 'Untitled',
            type        => 'str',
            order       => 9,
            placeholder => 'no caption text',
            doc         => 'The caption. Empty leaves the bar and its '
                . 'buttons with nothing written on them',
        },
        menu => {
            default     => 'File  Edit  Search  Help',
            type        => 'str',
            order       => 10,
            placeholder => 'no menu bar at all',
            doc         => 'The menu bar. Empty removes the bar rather than '
                . 'emptying it, because a blank strip of grey is not a menu',
        },
        font => {
            default => 'ui',
            type    => 'str',
            order   => 11,
            doc     => 'Font role or path for both strings. The ui role is '
                . 'W95FA where that is installed, which is what a window of '
                . 'this period set its caption in',
        },
        type_size => {
            default => 12,
            type    => 'int',
            min     => 12,
            max     => 18,
            order   => 12,
            doc     => 'Size of the caption and menu lettering. Never drawn '
                . 'smaller than the chosen font can manage, which for some '
                . 'faces is a pixel more than this',
        },
        scrollbars => {
            default => 1,
            type    => 'bool',
            order   => 13,
            doc     => 'A scroll bar down the right and along the bottom',
        },
        grip => {
            default => 1,
            type    => 'bool',
            order   => 14,
            needs   => { scrollbars => 1 },
            doc     => 'The sizing grip in the corner where they meet',
        },
        thumb => {
            default => 0.55,
            type    => 'num',
            min     => 0.05,
            max     => 1,
            order   => 15,
            needs   => { scrollbars => 1 },
            doc     => 'How much of its bar each thumb covers, which is how '
                . 'much of the document the window is saying it can see',
        },
        scroll => {
            default => 0.15,
            type    => 'num',
            min     => 0,
            max     => 1,
            order   => 16,
            needs   => { scrollbars => 1 },
            doc     => 'Where along its bar each thumb sits',
        },
        opacity => {
            default => 1,
            type    => 'num',
            min     => 0,
            max     => 1,
            order   => 17,
            doc     => 'Overall opacity of the window',
        },
        jitter => {
            animation => 1,
            default   => 0,
            type      => 'num',
            min       => 0,
            max       => 24,
            order     => 18,
            doc       => 'How far the window may jump from where it was put, '
                . "in the window's own pixels, redrawn every frame",
        },
    },
    apply => \&_chicago,
);

sub _chicago
{
    my ( $ctx, $p ) = @_;

    my ( $iw, $ih ) = $ctx->dims;
    return unless $iw && $ih;

    my $zoom = int( $p->{ zoom } || 0 ) || _chicago_zoom( $ih );

    # The window is asked for in the picture's pixels and built in its own, so
    # the division happens here and the module never hears about zoom.
    my $want_w = _round( $iw * $p->{ width } );
    my $want_h = _round( $ih * $p->{ height } );

    my $win = GlitchVape::Chicago::render(
        width      => int( $want_w / $zoom ),
        height     => int( $want_h / $zoom ),
        theme      => $p->{ theme },
        icon       => $p->{ icon },
        caption    => $p->{ title },
        menu       => $p->{ menu },
        font       => GlitchVape::Fonts::resolve( $p->{ font } ),
        type_size  => $p->{ type_size },
        scrollbars => $p->{ scrollbars },
        grip       => $p->{ grip },
        thumb      => $p->{ thumb },
        scroll     => $p->{ scroll },
    );

    # What it gave back rather than what was asked for: render() clamps up to
    # the smallest window its parts fit in, so a window asked to be narrower
    # than its own caption buttons comes back wider.
    my ( $cw, $ch ) = ( $win->Get( 'width' ), $win->Get( 'height' ) );

    if ( $zoom > 1 )
    {
        # Sample, not Resize. Sample replicates pixels; Resize interpolates,
        # and an interpolated one-pixel highlight is a grey smear that stops
        # the bevel reading as raised at all.
        GlitchVape::Magick::check(
            $win->Sample(
                geometry => sprintf '%dx%d!',
                $cw * $zoom, $ch * $zoom
            ),
            'chicago: could not enlarge the window'
        );
    }

    if ( $p->{ opacity } < 1 )
    {
        $win->Evaluate(
            operator => 'Multiply',
            value    => $p->{ opacity },
            channel  => 'Alpha',
        );
    }

    my ( $x, $y ) = _chicago_place( $p, $iw, $ih, $cw * $zoom, $ch * $zoom );
    ( $x, $y ) = _chicago_dance( $ctx, $p, $zoom, $x, $y );

    GlitchVape::Magick::check(
        $ctx->image->Composite(
            image   => $win->[ 0 ],
            compose => 'Over',
            x       => $x,
            y       => $y,
        ),
        'chicago: could not place the window'
    );

    return;
}

# A new place every frame, near the one it was put in. Not a drift: everywhere
# else here that word is a journey, a pattern travelling in a direction and
# snapped to whole repeats so that it arrives back where it set out. This is a
# window that will not sit still, which is a different thing and gets a
# different word.
#
# It closes its loop all the same, and by an easier route. Context::rng_phase
# keys the roll on where the frame sits around the loop rather than on which
# frame it is, so the frame after the last one is the first one again; and the
# seam is invisible regardless, because every frame is already somewhere else
# and one more jump among them reads as one more jump.
#
# Measured in the window's own pixels and multiplied up by the zoom, so the
# dance is the same size on the screen whatever the picture's resolution --
# and so the window stays on the grid it was drawn on, which a jump of some
# other number of image pixels would not disturb but would look arbitrary
# beside everything else here.
sub _chicago_dance
{
    my ( $ctx, $p, $zoom, $x, $y ) = @_;

    my $most = $p->{ jitter } || 0;

    return ( $x, $y ) if $most <= 0 || $ctx->frames <= 1;

    my $rng = $ctx->rng_phase( 'chicago' );

    return (
        $x + $zoom * _round( $rng->between( -$most, $most ) ),
        $y + $zoom * _round( $rng->between( -$most, $most ) ),
    );
}

# One window pixel per image pixel would leave a four-pixel border on a
# twelve-megapixel photograph, which is a hairline nobody would read as a
# window. The picture is treated as a screen 480 pixels tall -- the height of
# the screenshot every measurement in GlitchVape::Chicago came off -- and the
# zoom is however many times bigger than that it is.
sub _chicago_zoom
{
    my ( $height ) = @_;

    my $zoom = _round( $height / 480 );

    return $zoom < 1 ? 1 : $zoom;
}

# Insets from the anchor rather than plain offsets, which is what the rest of
# the overlay effects mean by x and y: at NorthEast a positive x moves the
# window left, because it is moving away from the edge it is against.
sub _chicago_place
{
    my ( $p, $iw, $ih, $ww, $wh ) = @_;

    my $dx = _round( $iw * $p->{ x } );
    my $dy = _round( $ih * $p->{ y } );

    my $gravity = $p->{ gravity } // 'Center';

    my $x =
          $gravity =~ /West/ ? $dx
        : $gravity =~ /East/ ? $iw - $ww - $dx
        :                      int( ( $iw - $ww ) / 2 ) + $dx;

    my $y =
          $gravity =~ /North/ ? $dy
        : $gravity =~ /South/ ? $ih - $wh - $dy
        :                       int( ( $ih - $wh ) / 2 ) + $dy;

    return ( $x, $y );
}

# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------

$R->register(
    name    => 'stars',
    title   => 'Starry Night',
    stage   => 'overlay',
    summary => 'The Norton Commander screensaver, twinkling over the picture',
    doc     => <<'DOC',
Norton Commander's Starry Night, drawn over the photograph: a text-mode sky
where most stars sit as a dim C<·> and, every so often, one flares up through
a ramp of larger characters, burns out, and comes back somewhere else.

The animation is the same sky later rather than a new sky each time, which is
the whole difference between a screensaver and a field of noise: what reads as
twinkling is that the stars stay where they are between the moments they do
not. A still is the sky two hundred steps in, so that flares are in progress
rather than about to begin -- a sky where nothing has happened yet is a grid
of identical dots. C<flare> is the pace, and under one a frame is a sky that
twinkles rather than boils.

C<dim> is the screen going dark behind it, which is what a screensaver does
before any of this starts. At 0 the stars are simply over the picture; at 1
the picture is gone and there is only the sky.

The loop does not close, and cannot: a star that flares comes back somewhere
else, so a sky that ended where it began would be a sky whose stars never
move. It joins C<grain> and C<static> in that, and for the same reason nobody
sees the join -- a handful of stars are somewhere else at every frame, so a
handful being somewhere else at that one is not a seam.

Drawn in the 8x16 text-mode font, scaled by pixel replication, in the sixteen
colours the hardware had. See L<GlitchVape::Starfield> for the sky and
L<GlitchVape::VGA> for the characters.
DOC
    params => {
        density => {
            default => 1.8,
            type    => 'num',
            min     => 0.1,
            max     => 10,
            order   => 1,
            doc     => 'Stars as a percentage of the character cells there '
                . 'are room for',
        },
        scale => {
            default => 2,
            type    => 'int',
            min     => 1,
            max     => 16,
            order   => 2,
            doc     => 'Image pixels per font pixel, so a cell is 8 by 16 '
                . 'of these',
        },
        color => {
            default => '#00AAAA',
            type    => 'str',
            order   => 3,
            needs   => { random => 0 },
            doc     => 'What a star at rest is drawn in. The original was '
                . 'teal, and flares are white whatever this says',
        },
        random => {
            label   => 'Random star colours',
            default => 0,
            type    => 'bool',
            order   => 4,
            doc     => 'Give every star its own colour from the sixteen the '
                . 'hardware had, and keep it when the star moves',
        },
        flare => {
            default => 0.6,
            type    => 'num',
            min     => 0,
            max     => 8,
            order   => 5,
            doc     => 'Stars that begin to flare each step. Under one is a '
                . 'sky that twinkles; several is one that boils',
        },
        dim => {
            default => 0,
            type    => 'num',
            min     => 0,
            max     => 1,
            order   => 6,
            doc     => 'How far the picture behind the sky is darkened. 1 is '
                . 'the screen blanking, which is what a screensaver does '
                . 'before it draws anything',
        },
        opacity => {
            default => 1,
            type    => 'num',
            min     => 0,
            max     => 1,
            order   => 7,
            doc     => 'How completely the stars replace what is under them',
        },
    },
    apply => \&_stars,
);

sub _stars
{
    my ( $ctx, $p ) = @_;

    return unless $p->{ opacity } > 0;

    # Before anything about the grid, and through ImageMagick rather than a
    # pixel at a time. The screen going dark is what a screensaver does before
    # it draws a single star, so it is not conditional on there being any --
    # a density that rounds down to no stars should still blank the screen,
    # not quietly do nothing.
    $ctx->image->Evaluate( operator => 'Multiply', value => 1 - $p->{ dim } )
        if $p->{ dim } > 0;

    my ( $w, $h ) = $ctx->dims;

    my $scale = $p->{ scale };
    my $cw    = GlitchVape::VGA::CELL_W * $scale;
    my $ch    = GlitchVape::VGA::CELL_H * $scale;

    my $columns = int( $w / $cw );
    my $rows    = int( $h / $ch );
    return if $columns < 1 || $rows < 1;

    my $stars = _round( $columns * $rows * $p->{ density } / 100 );
    return unless $stars > 0;

    # The step is the frame, so frame twelve is the sky after twelve more
    # steps than frame eleven's -- and a still is step nought, which is the
    # settled sky rather than a fresh one.
    my $sky = GlitchVape::Starfield::sky(
        rng     => $ctx->rng_fixed( 'stars' ),
        columns => $columns,
        rows    => $rows,
        stars   => $stars,
        flare   => $p->{ flare },
        step    => $ctx->frames > 1 ? $ctx->frame : 0,
    );

    my @ink  = _star_inks( $ctx, $p, $stars );
    my @ramp = GlitchVape::Starfield::ramp();
    my $hot  = pack 'C3', 255, 255, 255;

    GlitchVape::Pixels->edit(
        $ctx,
        sub {
            my ( $px ) = @_;

            # A cell rendered once is a cell rendered once, and a sky is
            # mostly the same dim character in the same colour.
            my %cell;

            for my $n ( 0 .. $#$sky )
            {
                my ( $col, $row, $bright ) = @{ $sky->[ $n ] };

                my $char = $ramp[ $bright ];
                my $fore = $bright ? $hot : $ink[ $n ];

                $cell{ "$char/$fore" } ||= GlitchVape::VGA::cell_rows(
                    char       => $char,
                    fore       => $fore,
                    back       => "\0\0\0",
                    scale      => $scale,
                    background => 0,
                );

                GlitchVape::VGA::blit(
                    px         => $px,
                    x          => $col * $cw,
                    y          => $row * $ch,
                    rows       => $cell{ "$char/$fore" },
                    scale      => $scale,
                    opacity    => $p->{ opacity },
                    background => 0,
                );
            }

            return;
        }
    );

    return;
}

# One colour per star, held for the life of the render so that a star keeps
# its colour when it burns out and comes back somewhere else. Its own stream,
# so that turning the switch on does not shift the sky underneath it.
sub _star_inks
{
    my ( $ctx, $p, $stars ) = @_;

    unless ( $p->{ random } )
    {
        return ( _star_ink( $p->{ color } ) ) x $stars;
    }

    my $rng     = $ctx->rng_fixed( 'stars:colour' );
    my @colours = GlitchVape::VGA::colours();

    # From one rather than nought: a black star on a dark sky is a star
    # nobody can see, and offering it as one in sixteen is offering a hole.
    return map { $colours[ $rng->int_between( 1, $#colours ) ] } 1 .. $stars;
}

# A colour nobody can read is teal, which is what the screensaver used. Not
# fatal: a preset with a typo in it should draw a sky, not stop the render.
sub _star_ink
{
    my ( $hex ) = @_;

    my @rgb = ( $hex // q{} ) =~
        m{ \A [#]? ([0-9a-f]{2}) ([0-9a-f]{2}) ([0-9a-f]{2}) \z }xi;

    return pack 'C3', 0, 170, 170 unless @rgb == 3;

    return pack 'C3', map { hex } @rgb;
}

# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------

$R->register(
    name    => 'maximised',
    title   => 'Maximised Window',
    stage   => 'framing',
    summary => 'The same 1995 window, with the picture inside it',
    doc     => <<'DOC',
C<chicago> drawn the other way round: instead of a window laid over the
picture with a hole in it, a window built I<around> the picture, the way a
maximised one is built around whatever it is showing.

So it takes no size and no position. A maximised window has neither -- it is
as big as what is in it plus its own furniture, and it is wherever the screen
is. It runs at C<framing> for the same reason C<letterbox> does: it makes the
picture bigger than the one it was handed, and everything that came before
happened to the picture rather than to the frame around it.

Two things follow from the window being maximised rather than floating, and
both are drawn rather than settable. Maximise becomes Restore, which is the
one thing on a caption that says which of the two a window is. And the sizing
grip goes, because a maximised window cannot be resized and offering a handle
for doing it would be a lie about what the picture is.

C<zoom> is how many image pixels one of the window's own pixels becomes, and
it is a whole number because the alternative is interpolation. Left at 0 it is
worked out from the picture, on the reading that the picture is a screen 480
pixels tall -- so a photograph under 720 pixels tall gets 1, and 0 and 1 draw
the same window there. A 1080-pixel one gets 2 and a 2160-pixel one gets 5.

The chrome is a whole number of window pixels across, so the client area is
too, and the picture is centred in it. What is left over is fewer pixels than
C<zoom> and shows as the application's own canvas -- which is what an image
viewer looks like anyway.
DOC
    params => {
        zoom => {
            default => 0,
            type    => 'int',
            min     => 0,
            max     => 12,
            order   => 1,
            doc     => 'Image pixels per window pixel. 0 reads the picture as '
                . 'a screen 480 tall and rounds, so anything under 720 gets '
                . '1 and 0 and 1 are the same there; 1080 gets 2, 2160 gets 5',
        },
        theme => {
            default => 'default',
            type    => 'enum',
            order   => 2,
            values  => [ GlitchVape::Chicago::themes() ],
            doc     => 'Which of the schemes from the Appearance tab the '
                . 'window is painted in',
        },
        icon => {
            default => 'glitchvape',
            type    => 'enum',
            order   => 3,
            values  => [ GlitchVape::Chicago::icons() ],
            doc     => 'The picture in the top left: this program, or the '
                . 'document page the window was scavenged from',
        },
        title => {
            default     => 'Untitled',
            type        => 'str',
            order       => 4,
            placeholder => 'no caption text',
            doc         => 'The caption. Empty leaves the bar and its '
                . 'buttons with nothing written on them',
        },
        menu => {
            default     => 'File  Edit  Search  Help',
            type        => 'str',
            order       => 5,
            placeholder => 'no menu bar at all',
            doc         => 'The menu bar. Empty removes the bar rather than '
                . 'emptying it, because a blank strip of grey is not a menu',
        },
        font => {
            default => 'ui',
            type    => 'str',
            order   => 6,
            doc     => 'Font role or path for both strings. The ui role is '
                . 'W95FA where that is installed, which is what a window of '
                . 'this period set its caption in',
        },
        type_size => {
            default => 12,
            type    => 'int',
            min     => 12,
            max     => 18,
            order   => 7,
            doc     => 'Size of the caption and menu lettering. Never drawn '
                . 'smaller than the chosen font can manage, which for some '
                . 'faces is a pixel more than this',
        },
        scrollbars => {
            default => 1,
            type    => 'bool',
            order   => 8,
            doc     => 'A scroll bar down the right and along the bottom, '
                . 'outside the picture rather than over it',
        },
        thumb => {
            default => 0.55,
            type    => 'num',
            min     => 0.05,
            max     => 1,
            order   => 9,
            needs   => { scrollbars => 1 },
            doc     => 'How much of its bar each thumb covers, which is how '
                . 'much of the document the window is saying it can see',
        },
        scroll => {
            default => 0.15,
            type    => 'num',
            min     => 0,
            max     => 1,
            order   => 10,
            needs   => { scrollbars => 1 },
            doc     => 'Where along its bar each thumb sits',
        },
    },
    apply => \&_maximised,
);

sub _maximised
{
    my ( $ctx, $p ) = @_;
    require Image::Magick;

    my ( $iw, $ih ) = $ctx->dims;
    return unless $iw && $ih;

    my $zoom = int( $p->{ zoom } || 0 ) || _chicago_zoom( $ih );

    my $menu = $p->{ menu };

    # The window is drawn a pixel at a time and then enlarged whole, so every
    # measurement in it is a multiple of the zoom -- the client area included.
    # Rounded up rather than down, so the picture is never cropped to make it
    # fit its own frame.
    my $cw = int( ( $iw + $zoom - 1 ) / $zoom );
    my $ch = int( ( $ih + $zoom - 1 ) / $zoom );

    my $win = GlitchVape::Chicago::render(
        client     => [ $cw, $ch ],
        maximised  => 1,
        theme      => $p->{ theme },
        icon       => $p->{ icon },
        caption    => $p->{ title },
        menu       => $menu,
        font       => GlitchVape::Fonts::resolve( $p->{ font } ),
        type_size  => $p->{ type_size },
        scrollbars => $p->{ scrollbars },
        thumb      => $p->{ thumb },
        scroll     => $p->{ scroll },
    );

    my ( $ww, $wh ) = ( $win->Get( 'width' ), $win->Get( 'height' ) );

    if ( $zoom > 1 )
    {
        # Sample, not Resize: see the note in _chicago.
        GlitchVape::Magick::check(
            $win->Sample(
                geometry => sprintf '%dx%d!',
                $ww * $zoom, $wh * $zoom
            ),
            'maximised: could not enlarge the window'
        );
    }

    my ( $hx, $hy ) = GlitchVape::Chicago::client_origin( menu => $menu );

    # The sliver: the client area rounded up to whole window pixels is at most
    # zoom-1 bigger than the picture, and the picture sits in the middle of it.
    my $out = Image::Magick->new(
        size => sprintf '%dx%d',
        $ww * $zoom, $wh * $zoom
    );
    $out->Read( 'xc:' . GlitchVape::Chicago::ink( $p->{ theme }, 'F' ) );

    GlitchVape::Magick::check(
        $out->Composite(
            image   => $ctx->image->[ 0 ],
            compose => 'Over',
            x       => $hx * $zoom + int( ( $cw * $zoom - $iw ) / 2 ),
            y       => $hy * $zoom + int( ( $ch * $zoom - $ih ) / 2 ),
        ),
        'maximised: could not place the picture in the window'
    );

    GlitchVape::Magick::check(
        $out->Composite( image => $win->[ 0 ], compose => 'Over' ),
        'maximised: could not draw the window around it'
    );

    $ctx->image( $out );

    return;
}

# ---------------------------------------------------------------------------

sub _round { return int( $_[ 0 ] + ( $_[ 0 ] < 0 ? -0.5 : 0.5 ) ) }

# Into one tile. Sliding by six tiles and by one look identical, so there is
# no reason to draw the other five off the edge of the canvas.
sub _wrap
{
    my ( $value, $period ) = @_;

    return 0 unless $period;

    $value -= $period * int( $value / $period );
    $value += $period if $value < 0;

    return $value;
}

# ---------------------------------------------------------------------------

sub _annotate
{
    my ( $ctx, %a ) = @_;

    my $img  = $ctx->image;
    my $text = Encode::encode( 'UTF-8', $a{ string } );

    # Fully opaque unless the caller asked otherwise; an explicit 0 must be
    # honoured rather than treated as "unset".
    my $opacity = 1;
    if ( defined $a{ opacity } )
    {
        $opacity = $a{ opacity };
    }

    my %args = (
        text      => $text,
        font      => $a{ font },
        pointsize => $a{ size },
        fill      => $a{ color },
        gravity   => $a{ gravity } // 'NorthWest',
        x         => int( $a{ x } // 0 ),
        y         => int( $a{ y } // 0 ),
        encoding  => 'UTF-8',
        antialias => 'true',
    );
    $args{ rotate } = $a{ rotate } if $a{ rotate };

    if ( $opacity < 1 )
    {
        # Annotate has no opacity control, so draw onto a transparent layer,
        # fade it, and composite.
        require Image::Magick;
        my ( $w, $h ) = $ctx->dims;

        my $layer = Image::Magick->new( size => "${w}x${h}" );
        $layer->Read( 'xc:transparent' );
        GlitchVape::Magick::check( $layer->Annotate( %args ),
            "text: could not render with font '$a{font}'" );

        $layer->Evaluate(
            operator => 'Multiply',
            value    => $opacity,
            channel  => 'Alpha',
        );
        $img->Composite( image => $layer->[ 0 ], compose => 'Over' );
        return;
    }

    GlitchVape::Magick::check( $img->Annotate( %args ),
        "text: could not render with font '$a{font}'" );
    return;
}

1;
