package GlitchVape::Effect::Overlay;

use strict;
use warnings;
use utf8;

use Encode ();

use GlitchVape::Magick   ();
use GlitchVape::Registry ();
use GlitchVape::Fonts    ();
use GlitchVape::Palette  ();

our $VERSION = '0.01';

=head1 NAME

GlitchVape::Effect::Overlay - text, camcorder furniture and drawn graphics

=head1 DESCRIPTION

Everything drawn on top of the picture rather than done to it. These run last,
because on-screen display is generated by the camera or the player and is not
subject to the tape damage the picture went through -- which is exactly why
crisp white C<REC> text over a degraded image reads as authentic.

=cut

my $R  = 'GlitchVape::Registry';
my $PI = 3.14159265358979;

# Stock phrases. Mostly the words the genre actually uses, which are not always
# the words a translation would pick: 蒸気波 is a literal calque of "vapor
# wave" that exists because of the genre, not before it.
my @PHRASES = (
    'ヴェイパーウェイブ',    # vaporwave
    '蒸気波',          # vapor wave (calque)
    '美的',           # aesthetic
    '未来',           # future
    '夢',            # dream
    '無限',           # infinity
    '電脳',           # cyber
    '東京',           # Tokyo
    '音楽',           # music
    '現実を超えて',       # beyond reality
    '記憶',           # memory
    '孤独',           # solitude
    '夜',            # night
    '水',            # water
    '新世紀',          # new century
);

# ---------------------------------------------------------------------------

$R->register(
    name    => 'text',
    title   => 'Text',
    stage   => 'overlay',
    summary => 'Draw text over the image',
    doc     => <<'DOC',
Renders a string, defaulting to a randomly chosen Japanese phrase from a built
in list. C<random> says what that choice does across a loop -- redrawn every
frame, which is the default and is what makes the text flicker; held for the
whole render; or not made at all. The C<shadow> offset draws the same text in a contrasting colour
behind the main copy, which is what stops light text disappearing into a light
background.
DOC
    params => {
        string => {
            default => '',
            type    => 'str',
            doc     => 'Text to draw; empty picks a random Japanese phrase',
        },
        random => {
            default => 'frame',
            type    => 'enum',
            values  => [ qw(frame once off) ],
            doc     => 'What an empty string means: frame, a new phrase every '
                . 'frame; once, one phrase held for the whole render; off, '
                . 'nothing drawn at all',
        },
        font => {
            default => 'cjk',
            type    => 'str',
            doc     => 'Font role (cjk, vcr, pixel, mono, sans) or a font path',
        },
        size => {
            default => 12,
            type    => 'num',
            min     => 0.5,
            max     => 100,
            doc     => 'Height of the type as a percentage of the image height',
        },
        gravity => {
            default => 'Center',
            type    => 'enum',
            values  => [
                qw(NorthWest North NorthEast West Center East
                    SouthWest South SouthEast)
            ],
            doc => 'Where the text sits',
        },
        color => {
            default => '#FFFFFF',
            type    => 'str',
            doc     => 'Fill colour',
        },
        shadow => {
            default => '#FF00AA',
            type    => 'str',
            doc     => 'Offset copy drawn behind; empty to disable',
        },
        shadow_offset => {
            default => 4,
            type    => 'num',
            min     => -100,
            max     =>  100,
            doc     => 'Shadow displacement in pixels',
        },
        opacity => {
            default => 0.9,
            type    => 'num',
            min     => 0,
            max     => 1,
            doc     => 'Text opacity',
        },
        x => {
            default => 0.04,
            type    => 'num',
            min     => -1,
            max     =>  1,
            doc     => 'Horizontal inset as a fraction of width',
        },
        y => {
            default => 0.04,
            type    => 'num',
            min     => -1,
            max     =>  1,
            doc     => 'Vertical inset as a fraction of height',
        },
        rotate => {
            default => 0,
            type    => 'num',
            min     => -180,
            max     =>  180,
            doc     => 'Rotation in degrees',
        },
        spacing => {
            default => 0,
            type    => 'num',
            min     => -50,
            max     => 200,
            doc     => 'Extra letter spacing; wide tracking is a genre staple',
        },
    },
    apply => \&_text,
);

sub _text
{
    my ( $ctx, $p ) = @_;
    return if $p->{ opacity } <= 0;

    # An empty string means "surprise me", which is how the presets get
    # varied Japanese text without naming a phrase in every one.
    #
    # What it left unsaid was how often the surprise is repeated. rng_for
    # folds the frame index in, so a loop drew a new phrase on every frame --
    # which is the wanted behaviour and stays the default, but was arrived at
    # by accident of which stream the effect happened to ask for rather than
    # by anybody choosing it. It is a stated choice now, and 'once' is there
    # for a caption that is supposed to sit still.
    my $str = $p->{ string };

    if ( !length $str )
    {
        my $when = $p->{ random } // 'frame';

        return if $when eq 'off';

        # rng_fixed for 'once', which is the same stream on every frame of the
        # loop; rng_for for 'frame', which is not.
        my $rng =
              $when eq 'frame'
            ? $ctx->rng_for( 'text' )
            : $ctx->rng_fixed( 'text' );

        $str = $rng->pick( @PHRASES );
    }

    # Wide tracking is done by hand because ImageMagick has no letter-spacing
    # control; inserting thin spaces is the usual workaround.
    if ( $p->{ spacing } > 0 )
    {
        my $gap = ' ' x ( int( $p->{ spacing } / 8 ) || 1 );
        $str = join $gap, split //, $str;
    }

    my ( $w, $h ) = $ctx->dims;
    my $font =
        GlitchVape::Fonts::resolve_or_die( $p->{ font }, "effect 'text'" );
    my $size = int( $h * $p->{ size } / 100 ) || 8;

    my $dx = int( $w * $p->{ x } );
    my $dy = int( $h * $p->{ y } );

    my %common = (
        string  => $str,
        font    => $font,
        size    => $size,
        gravity => $p->{ gravity },
        opacity => $p->{ opacity },
        rotate  => $p->{ rotate },
    );

    if ( length $p->{ shadow } && $p->{ shadow_offset } )
    {
        _annotate(
            $ctx, %common,
            color => $p->{ shadow },
            x     => $dx + $p->{ shadow_offset },
            y     => $dy + $p->{ shadow_offset },
        );
    }

    _annotate( $ctx, %common, color => $p->{ color }, x => $dx, y => $dy );
    return;
}

# ---------------------------------------------------------------------------

$R->register(
    name    => 'osd',
    title   => 'Camcorder OSD',
    stage   => 'overlay',
    summary => 'Camcorder on-screen display: REC, timestamp, tape mode',
    doc     => <<'DOC',
The furniture a 1990s camcorder burned into the picture. Defaults place a
blinking record indicator top-left and a date/time bottom-right, which is where
most consumer models actually put them.

The timestamp is invented by default -- a real present-day date on a vaporwave
image is an anachronism that undercuts the whole effect. Turn `invent` off and
`date` and `time` are drawn exactly as they are typed; either of them left
empty is simply not drawn, which is how to have a time and no date.
DOC
    params => {
        color => {
            order   => 10,
            label   => 'Colour',
            default => '#FFFFFF',
            type    => 'str',
            doc     => 'Text colour',
        },
        font => {
            order   => 20,
            label   => 'Font',
            default => 'vcr',
            type    => 'str',
            doc     => 'Font role or path',
        },
        size => {
            order   => 30,
            label   => 'Text size',
            default => 4.5,
            type    => 'num',
            min     => 0.5,

            # It was 50, which is an SP that fills half the frame -- and a
            # slider whose every usable value sat in its first tenth. This is
            # camcorder furniture, so it has a size: roughly the 4.5% below,
            # and 12 is already taller than anything a deck ever burned in.
            # The caption effects keep their 100, because oversized type is
            # the point of a caption and not of an OSD.
            max => 12,
            doc => 'Height of the type as a percentage of the image height',
        },
        margin => {
            order   => 40,
            label   => 'Margin',
            default => 0.045,
            type    => 'num',
            min     => 0,
            max     => 0.5,
            doc     => 'Inset from the edges',
        },
        timestamp => {
            order   => 50,
            label   => 'Timestamp',
            default => 1,
            type    => 'bool',
            doc     => 'Draw the date and time',
        },
        invent => {
            order   => 60,
            label   => 'Invent timestamp',
            default => 1,
            type    => 'bool',
            needs   => { timestamp => 1 },
            doc     => 'Make up a 1990s date and time from the seed, '
                . 'ignoring the two fields below',
        },
        date => {
            order   => 70,
            label   => 'Date',
            default => 'JUN 15 1995',
            type    => 'str',
            needs   => { timestamp => 1, invent => 0 },
            doc     => 'Date as it should read; empty draws no date',
        },
        time => {
            order   => 80,
            label   => 'Time',
            default => 'PM  3:47',
            type    => 'str',
            needs   => { timestamp => 1, invent => 0 },
            doc     => 'Time as it should read; empty draws no time',
        },
        camera => {
            order   => 90,
            label   => 'Camera mode',
            default => 'REC',
            type    => 'str',
            suggest => [ 'REC', 'PLAY', 'PLAY-FF' ],
            doc     => 'Transport indicator, top left; empty draws none',
        },
        rec_mode => {
            order   => 100,
            label   => 'DV REC mode',
            default => 'SP',
            type    => 'str',
            suggest => [ qw(SP LP HD) ],
            doc     => 'Tape speed, top right; empty to omit',
        },
        reroll => {
            order     => 110,
            label     => 'Varying timestamp',
            default   => 0,
            type      => 'bool',
            animation => 1,
            needs     => { timestamp => 1, invent => 1 },
            doc       => 'Invent a new timestamp on every frame, so the '
                . 'clock cannot settle on a date',
        },
        blink => {
            order     => 120,
            label     => 'Icon blink',
            default   => 1,
            type      => 'bool',
            animation => 1,
            needs     => { camera => 1 },
            doc       => 'Flash the camera indicator across the loop',
        },
    },
    apply => \&_osd,
);

# What a camera mode draws beside its label. A known transport state has a
# glyph the hardware drew; anything typed in is text alone, because a glyph
# guessed from an unrecognised word would be inventing a claim about what the
# deck is doing.
my %CAMERA_GLYPH = (
    'REC'     => 'dot',
    'PLAY'    => 'play',
    'PLAY-FF' => 'ff',
);

sub _osd
{
    my ( $ctx, $p ) = @_;

    my ( $w, $h ) = $ctx->dims;

    # Which stream the invented date comes out of is the whole of `reroll`.
    #
    # rng_fixed is the same numbers on every frame, and is the default because
    # a camcorder's clock is a fact about when the tape was made: it does not
    # change within two seconds of footage, and one that did read as a bug.
    #
    # rng_for folds the frame index in, so the display cannot settle on a date
    # at all. That was what this did by accident, and it turns out to be worth
    # keeping: a timestamp riffling through a decade is a picture of not
    # remembering when something happened, which is a thing several of these
    # presets are about. It is an answer to a different question, so it is a
    # setting rather than the default.
    my $rng =
          $p->{ reroll }
        ? $ctx->rng_for( 'osd' )
        : $ctx->rng_fixed( 'osd' );
    my $font =
        GlitchVape::Fonts::resolve_or_die( $p->{ font }, "effect 'osd'" );
    my $size = int( $h * $p->{ size } / 100 ) || 10;

    # Every piece of on-screen display shares its face, size and colour; only
    # the string and corner change.
    my %osd = ( font => $font, size => $size, color => $p->{ color } );

    # Where the corners are, kept beside the type it has to line up with:
    # three numbers that every piece of the display needs and none of them
    # varies, which is one argument rather than three at each call.
    my $box = {
        mx   => int( $w * $p->{ margin } ),
        my   => int( $h * $p->{ margin } ),
        size => $size,
        osd  => \%osd,
    };

    _osd_camera( $ctx, $p, $box );
    _osd_timestamp( $ctx, $p, $box, $rng );

    if ( length $p->{ rec_mode } )
    {
        _annotate(
            $ctx, %osd,
            string  => $p->{ rec_mode },
            gravity => 'NorthEast',
            x       => $box->{ mx },
            y       => $box->{ my },
        );
    }
    return;
}

# One indicator, not one per transport state. rec and play were separate
# switches with a separate label each, which made "REC and PLAY at once" a
# reachable setting -- a deck is in one transport state, and offering the
# other thing was offering a picture no camcorder ever showed.
sub _osd_camera
{
    my ( $ctx, $p, $box ) = @_;

    my ( $mx, $my, $size ) = @{ $box }{ qw(mx my size) };

    my $mode = $p->{ camera };
    return unless length $mode;

    # The whole indicator blinks, glyph and label together, which is what a
    # camcorder in standby actually does -- and what makes the setting mean
    # something for a mode typed in by hand, which has no glyph to flash.
    if ( $ctx->frames > 1 && $p->{ blink } && $ctx->phase >= 0.6 )
    {
        return;
    }

    my $glyph = $CAMERA_GLYPH{ uc $mode };
    my $x     = $mx;

    if ( $glyph )
    {
        _osd_glyph( $ctx, $p, $glyph, $box );

        # Past whatever was drawn, which is wider for the two triangles of a
        # fast wind than for the one of a play.
        $x = $mx + int( $size * ( $glyph eq 'ff' ? 1.4 : 0.95 ) );
    }

    _annotate(
        $ctx, %{ $box->{ osd } },
        string  => $mode,
        gravity => 'NorthWest',
        x       => $x,
        y       => $my,
    );

    return;
}

sub _osd_glyph
{
    my ( $ctx, $p, $glyph, $box ) = @_;

    my ( $mx, $my, $size ) = @{ $box }{ qw(mx my size) };

    my $r  = int( $size * 0.32 );
    my $cy = $my + int( $size * 0.42 );

    if ( $glyph eq 'dot' )
    {
        # Red whatever the text colour is: the record lamp was a red LED, and
        # a white one reads as a full stop.
        my $cx = $mx + $r;
        $ctx->magick( '-fill', '#FF2020', '-stroke', 'none', '-draw',
            sprintf( 'circle %d,%d %d,%d', $cx, $cy, $cx + $r, $cy ),
        );
        return;
    }

    my $tri = int( $size * 0.45 );
    my $top = $cy - $tri;

    # Two triangles for a fast wind, one for play -- the same shorthand as the
    # buttons on the deck, so the picture reads without the label.
    my @x = ( $mx );
    push @x, $mx + int( $tri * 1.05 ) if $glyph eq 'ff';

    for my $x0 ( @x )
    {
        $ctx->magick(
            '-fill',
            $p->{ color },
            '-stroke',
            'none', '-draw',
            sprintf(
                'polygon %d,%d %d,%d %d,%d',
                $x0,             $top,             $x0,
                $top + $tri * 2, $x0 + $tri * 1.7, $top + $tri
            ),
        );
    }

    return;
}

sub _osd_timestamp
{
    my ( $ctx, $p, $box, $rng ) = @_;

    my ( $mx, $my, $size ) = @{ $box }{ qw(mx my size) };

    return unless $p->{ timestamp };

    # Invented or literal, never a mixture. It used to be that an empty field
    # meant "invent this one", which made the difference between a made-up
    # date and a typed one invisible in the interface and impossible to state
    # in --explain: the switch says it instead, and an empty field now means
    # the one plain thing it looks like it means.
    my ( $date, $time ) = ( $p->{ date }, $p->{ time } );
    if ( $p->{ invent } )
    {
        $date = _fake_date( $rng );
        $time = _fake_time( $rng );
    }

    if ( length $time )
    {
        _annotate(
            $ctx, %{ $box->{ osd } },
            string  => $time,
            gravity => 'SouthEast',
            x       => $mx,
            y       => $my,
        );
    }

    if ( length $date )
    {
        _annotate(
            $ctx, %{ $box->{ osd } },
            string  => $date,
            gravity => 'SouthEast',
            x       => $mx,
            y       => $my + int( $size * 1.25 ),
        );
    }

    return;
}

my @MONTH = qw(JAN FEB MAR APR MAY JUN JUL AUG SEP OCT NOV DEC);

sub _fake_date
{
    my ( $rng ) = @_;
    return sprintf '%s %02d %d',
        $rng->pick( @MONTH ),
        $rng->int_between( 1,    28 ),
        $rng->int_between( 1990, 1999 );
}

sub _fake_time
{
    my ( $rng ) = @_;

    # 12-hour with a leading space, the way the cheap OSD chips rendered it.
    my $meridiem = 'PM';
    if ( $rng->chance( 0.5 ) )
    {
        $meridiem = 'AM';
    }

    return sprintf '%s %2d:%02d',
        $meridiem,
        $rng->int_between( 1, 12 ),
        $rng->int_between( 0, 59 );
}

# ---------------------------------------------------------------------------

$R->register(
    name    => 'grid',
    title   => 'Perspective Grid',
    stage   => 'overlay',
    summary => 'Retro perspective grid and sun',
    doc     => <<'DOC',
The synthwave horizon: a ground plane receding to a vanishing point, optionally
with a banded sun sitting on it. Horizontal line spacing follows a power curve
so the lines bunch up towards the horizon the way perspective actually makes
them, rather than being evenly spaced.
DOC
    params => {
        horizon => {
            default => 0.62,
            type    => 'num',
            min     => 0.05,
            max     => 0.95,
            doc     => 'Horizon height as a fraction from the top',
        },
        lines_h => {
            default => 14,
            type    => 'int',
            min     => 0,
            max     => 200,
            doc     => 'Number of horizontal lines',
        },
        lines_v => {
            default => 22,
            type    => 'int',
            min     => 0,
            max     => 200,
            doc     => 'Number of converging vertical lines',
        },
        color => {
            default => '#FF00AA',
            type    => 'str',
            doc     => 'Grid line colour',
        },
        width => {
            default => 2,
            type    => 'num',
            min     => 0.2,
            max     => 20,
            doc     => 'Line width in pixels',
        },
        opacity => {
            default => 0.75,
            type    => 'num',
            min     => 0,
            max     => 1,
            doc     => 'Grid opacity',
        },
        perspective => {
            default => 2.2,
            type    => 'num',
            min     => 1,
            max     => 8,
            doc => 'How hard the horizontal lines bunch towards the horizon',
        },
        drift => {
            animation => 1,
            default   => 0,
            type      => 'num',
            min       => -64,
            max       =>  64,
            doc       => 'Grid lines travelled per loop; negative recedes',
        },
        sun => {
            default => 1,
            type    => 'bool',
            doc     => 'Draw the banded sun',
        },
        sun_size => {
            default => 0.22,
            type    => 'num',
            min     => 0.02,
            max     => 1,
            doc     => 'Sun diameter as a fraction of image width',
        },
        sun_colors => {
            default => '#FFE261,#FF3864',
            type    => 'str',
            doc     => 'Top and bottom colours of the sun gradient',
        },
        sun_bands => {
            default => 7,
            type    => 'int',
            min     => 0,
            max     => 60,
            doc     => 'Slots cut across the lower half of the sun',
        },
    },
    apply => \&_grid,
);

sub _grid
{
    my ( $ctx, $p ) = @_;
    return if $p->{ opacity } <= 0;
    require Image::Magick;

    my ( $w, $h ) = $ctx->dims;
    my $hy = int( $h * $p->{ horizon } );
    my $cx = int( $w / 2 );

    my $layer = Image::Magick->new( size => "${w}x${h}" );
    GlitchVape::Magick::check( $layer->Read( 'xc:transparent' ),
        "grid: could not create layer" );

    _draw_sun( $layer, $p, $w, $h ) if $p->{ sun };

    my @draw;

    # Horizontal lines: t^perspective spaces them tightly at the horizon and
    # widely at the bottom of the frame.
    #
    # Drift moves them along that curve rather than down the screen, which is
    # the whole trick: a line travelling at constant speed in t accelerates
    # towards the viewer exactly as the spacing widens, so the plane reads as
    # ground going past instead of as stripes sliding. One line spacing is the
    # repeat, so travel() snaps to whole lines and the loop closes with a line
    # sitting where its neighbour started.
    #
    # Only these move. The vertical lines converge on the vanishing point and
    # are the same set of rays whatever the ground is doing; scrolling them
    # would swing the whole plane sideways.
    my $shift = $ctx->travel( $p->{ drift }, 1 );
    my $extra = int( abs $p->{ drift } ) + 1;

    for my $i ( 1 - $extra .. $p->{ lines_h } + $extra )
    {
        my $t = ( $i + $shift ) / $p->{ lines_h };

        # Off the top past the horizon, or off the bottom of the frame.
        next if $t <= 0 || $t > 1;

        my $y = $hy + ( $h - $hy ) * ( $t**$p->{ perspective } );
        push @draw, sprintf( 'line 0,%.1f %d,%.1f', $y, $w, $y );
    }

    # Vertical lines all converge on the vanishing point. Spreading their
    # bottom ends well past the frame edges keeps the outermost ones steep
    # enough to look like part of the same plane.
    if ( $p->{ lines_v } )
    {
        my $spread = $w * 2.5;
        for my $i ( 0 .. $p->{ lines_v } )
        {
            my $t = $i / $p->{ lines_v };
            my $x = $cx - $spread / 2 + $spread * $t;
            push @draw, sprintf( 'line %d,%d %.1f,%d', $cx, $hy, $x, $h );
        }
    }

    if ( @draw )
    {
        for my $d ( @draw )
        {
            my ( $prim, @pts ) = split ' ', $d;
            $layer->Draw(
                primitive   => $prim,
                points      => join( ' ', @pts ),
                stroke      => $p->{ color },
                strokewidth => $p->{ width },
                fill        => 'none',
                antialias   => 'true',
            );
        }
    }

    if ( $p->{ opacity } < 1 )
    {
        $layer->Evaluate(
            operator => 'Multiply',
            value    => $p->{ opacity },
            channel  => 'Alpha',
        );
    }

    $ctx->image->Composite( image => $layer->[ 0 ], compose => 'Over' );
    return;
}

sub _draw_sun
{
    my ( $layer, $p, $w, $h ) = @_;
    require Image::Magick;

    # Horizon and centre are derived rather than passed in: they are a
    # function of the geometry the caller already hands over.
    my $hy = int( $h * $p->{ horizon } );
    my $cx = int( $w / 2 );

    my $d = int( $w * $p->{ sun_size } );
    return if $d < 4;
    my $r = int( $d / 2 );

    my @cols = split /\s*,\s*/, $p->{ sun_colors };
    push @cols, $cols[ 0 ] if @cols < 2;

    # Build the sun as its own square image: a vertical gradient masked by a
    # circle. Drawing a gradient-filled circle directly is not something
    # ImageMagick's draw primitives can do.
    my $disc = Image::Magick->new( size => "${d}x${d}" );
    $disc->Read( "gradient:$cols[0]-$cols[1]" );

    my $mask = Image::Magick->new( size => "${d}x${d}" );
    $mask->Read( 'xc:black' );
    $mask->Draw(
        primitive => 'circle',
        points    => sprintf( '%d,%d %d,%d', $r, $r, $r, 0 ),
        fill      => 'white',
        stroke    => 'none',
    );

    # Slots across the lower half, widening towards the bottom.
    if ( $p->{ sun_bands } )
    {
        for my $i ( 1 .. $p->{ sun_bands } )
        {
            my $t  = $i / ( $p->{ sun_bands } + 1 );
            my $y  = $r + ( $d - $r ) * ( $t**1.4 );
            my $th = 1 + $t * $r * 0.16;
            $mask->Draw(
                primitive   => 'line',
                points      => sprintf( '0,%.1f %d,%.1f', $y, $d, $y ),
                stroke      => 'black',
                strokewidth => $th,
                fill        => 'none',
            );
        }
    }

    # The mask carries the shape as black and white pixels, so its intensity
    # has to be moved into its alpha channel before the composite. IM6's
    # CopyOpacity fell back to intensity when the source had no alpha; IM7
    # aliases CopyOpacity to CopyAlpha, which copies the alpha channel and
    # nothing else -- and `xc:black` arrives with a fully opaque one. Without
    # the copy the sun composites as an opaque square with no slots in it.
    $mask->Set( alpha => 'copy' );

    $disc->Set( alpha => 'on' );
    $disc->Composite( image => $mask->[ 0 ], compose => 'CopyAlpha' );

    my $x = $cx - $r;
    my $y = $hy - int( $r * 1.15 );

    $layer->Composite(
        image   => $disc->[ 0 ],
        compose => 'Over',
        x       => $x,
        y       => $y
    );
    return;
}

# ---------------------------------------------------------------------------

$R->register(
    name    => 'letterbox',
    title   => 'Letterbox & Border',
    stage   => 'framing',
    summary => 'Black bars, or a border around the frame',
    doc     => <<'DOC',
Crops to a target aspect ratio with bars, or draws a plain inset border. Bars
sell the "recorded off a broadcast" idea; a border reads more like a photo
print.
DOC
    params => {
        ratio => {
            default => '16:9',
            type    => 'str',
            suggest => 'ratio',
            doc     => 'Target aspect, e.g. "16:9" or "4:3"; empty to skip',
        },
        color => {
            default => 'black',
            type    => 'str',
            doc     => 'Bar or border colour',
        },
        border => {
            default => 0,
            type    => 'num',
            min     => 0,
            max     => 0.5,
            doc     => 'Uniform border as a fraction of the shorter side',
        },
    },
    apply => \&_letterbox,
);

sub _letterbox
{
    my ( $ctx, $p ) = @_;

    if ( length $p->{ ratio } )
    {
        my ( $rw, $rh ) =
            $p->{ ratio } =~
            m{^\s*(\d+(?:\.\d+)?)\s*[:x/]\s*(\d+(?:\.\d+)?)\s*$}
            or die
            "letterbox: ratio must look like '16:9', got '$p->{ratio}'\n";

        my ( $w, $h ) = $ctx->dims;
        my $target = $rw / $rh;
        my $cur    = $w / $h;

        my ( $nw, $nh ) =
            $cur > $target
            ? ( $w, int( $w / $target ) )
            : ( int( $h * $target ), $h );

        $ctx->magick(
            '-background', $p->{ color }, '-gravity', 'Center',
            '-extent',     "${nw}x${nh}",
        );
    }

    if ( $p->{ border } > 0 )
    {
        my ( $w, $h ) = $ctx->dims;

        # Border width is a fraction of the shorter side, so a panorama does
        # not get an absurdly thick frame on its short edge.
        my $shorter = $h;
        if ( $w < $h )
        {
            $shorter = $w;
        }

        my $b = int( $shorter * $p->{ border } );
        $ctx->magick( '-bordercolor', $p->{ color }, '-border', $b ) if $b > 0;
    }
    return;
}

# ---------------------------------------------------------------------------

$R->register(
    name    => 'watermark',
    title   => 'Tiled Watermark',
    stage   => 'overlay',
    summary => 'Tiled repeating text across the whole frame',
    doc     => <<'DOC',
Repeats a string in a low-contrast grid over the image, in the manner of a
stock-photo proof or a corrupted screensaver.

C<drift> slides the whole tiling along the text's own reading direction, so
with C<rotate> set the motion comes out diagonal and the thing reads as the
screensaver it is imitating. This is the effect that animates most cleanly of
any of them, and for a reason worth knowing: a tiled pattern has an exact
period, so moving it a whole number of tiles per loop returns it to itself
with nothing to hide and no speed at which it goes wrong. Everything else that
drifts has to snap or rock to close its loop; this one simply closes.
DOC
    params => {
        string => {
            default => '美的',
            type    => 'str',
            doc     => 'Text to repeat',
        },
        font => {
            default => 'cjk',
            type    => 'str',
            doc     => 'Font role or path',
        },
        size => {
            default => 5,
            type    => 'num',
            min     => 0.5,
            max     => 100,
            doc     => 'Height of the type as a percentage of the image height',
        },
        color => {
            default => '#FFFFFF',
            type    => 'str',
            doc     => 'Text colour',
        },
        opacity => {
            default => 0.12,
            type    => 'num',
            min     => 0,
            max     => 1,
            doc     => 'Overall opacity',
        },
        rotate => {
            default => -30,
            type    => 'num',
            min     => -180,
            max     =>  180,
            doc     => 'Rotation of the tiled text',
        },
        spacing => {
            default => 2.2,
            type    => 'num',
            min     => 1,
            max     => 12,
            doc     => 'Gap between repetitions, in multiples of text size',
        },
        drift => {
            animation => 1,
            default   => 0,
            type      => 'num',
            min       => -32,
            max       =>  32,
            doc       => 'Tiles the pattern slides per loop; negative reverses',
        },
        direction => {
            animation => 1,
            default   => 'east',
            type      => 'enum',
            values    => [
                qw(north northeast east southeast
                    south southwest west northwest)
            ],
            doc => 'Compass direction the pattern slides, on the screen',
        },
    },
    apply => \&_watermark,
);

sub _watermark
{
    my ( $ctx, $p ) = @_;
    return if $p->{ opacity } <= 0;
    require Image::Magick;

    my ( $w, $h ) = $ctx->dims;
    my $font =
        GlitchVape::Fonts::resolve_or_die( $p->{ font }, "effect 'watermark'" );
    my $size = int( $h * $p->{ size } / 100 ) || 8;

    # Rotating the finished layer means building it on an oversized canvas so
    # the corners are still covered afterwards. The diagonal is the minimum
    # that can contain the frame at any angle; the margin on top covers the
    # tile that is half in shot at the edge.
    my $diag = int( sqrt( $w * $w + $h * $h ) ) + $size * 4;

    my $layer = Image::Magick->new( size => "${diag}x${diag}" );
    $layer->Read( 'xc:transparent' );

    my $text = Encode::encode( 'UTF-8', $p->{ string } );
    my $gap  = int( $size * $p->{ spacing } ) || $size;

    # How wide the string actually comes out, rather than how wide a character
    # of it is. Spacing the columns on the point size alone works only while
    # the string is about as wide as it is tall: give it a sentence and every
    # repetition is drawn across the next one, and the whole band turns into a
    # smear. Asking the font settles it for any string in any face.
    my @metrics = $layer->QueryFontMetrics(
        text      => $text,
        font      => $font,
        pointsize => $size,
        encoding  => 'UTF-8',
    );
    my $ink = $metrics[ 4 ] || $size;

    # The lattice. Horizontally a repetition plus its gap, so two of them
    # never touch; vertically two rows, because the odd ones are staggered and
    # it takes two to come back to the same offset.
    my $xperiod = int( $ink + $gap );
    my $yperiod = $gap * 2;

    my ( $sx, $sy ) = _watermark_slide( $ctx, $p, $xperiod, $yperiod );

    # Enough margin that whatever is sliding in from either side is already
    # drawn by the time it arrives.
    my $row = 0;
    for ( my $y = -$yperiod ; $y < $diag + $yperiod ; $y += $gap )
    {
        # Every other row offset by half a tile, so the tiling reads as a
        # scatter rather than as columns.
        my $stagger = $row++ % 2 ? int( $xperiod / 2 ) : 0;

        for ( my $x = -$xperiod ; $x < $diag + $xperiod ; $x += $xperiod )
        {
            $layer->Annotate(
                text      => $text,
                font      => $font,
                pointsize => $size,
                fill      => $p->{ color },
                x         => $x + $stagger + $sx,
                y         => $y + $sy,
                gravity   => 'NorthWest',
                encoding  => 'UTF-8',
                antialias => 'true',
            );
        }
    }

    $layer->Rotate( degrees => $p->{ rotate }, background => 'transparent' );

    # Before the crop, not after. Rotate leaves the layer with a virtual
    # canvas offset describing where the original sat inside the new bounds,
    # and Crop measures from that rather than from the pixels -- so the window
    # comes off the corner of the rotated square instead of its middle, and a
    # wedge of the frame ends up with no watermark on it at all. It is not a
    # small wedge: at 45 degrees it was a seventh of the picture.
    $layer->Set( page => '0x0+0+0' );

    $layer->Set( gravity => 'Center' );
    $layer->Crop( geometry => "${w}x${h}+0+0", gravity => 'Center' );
    $layer->Set( page => '0x0+0+0' );

    $layer->Evaluate(
        operator => 'Multiply',
        value    => $p->{ opacity },
        channel  => 'Alpha',
    );

    $ctx->image->Composite(
        image   => $layer->[ 0 ],
        compose => 'Over',
        gravity => 'Center',
    );
    return;
}

# Screen-space unit vectors, y downward as the raster has it.
#
# Written out rather than abbreviated, because the text effect's `gravity`
# spells its compass in full and two effects naming the same eight directions
# two different ways is a thing to remember for no reason. 'se' also has to be
# decoded every time it is read, and a preset is read far more often than it
# is written.
my %COMPASS = (
    north     => [  0, -1 ],
    northeast => [  1, -1 ],
    east      => [  1,  0 ],
    southeast => [  1,  1 ],
    south     => [  0,  1 ],
    southwest => [ -1,  1 ],
    west      => [ -1,  0 ],
    northwest => [ -1, -1 ],
);

# Where the tiling has slid to by this frame, as ( x, y ) in layer pixels.
#
# The direction is asked for on the screen, but the sliding happens on the
# layer, before it is turned by C<rotate>. So the compass vector is turned the
# other way first, and then rounded to a whole number of tiles on each axis --
# because only whole tiles bring the pattern back to itself, and a loop that
# does not come back jolts once per repeat forever.
#
# Rounding is what makes the direction approximate whenever C<rotate> is not a
# multiple of a right angle, and the approximation is better the further the
# pattern travels: one tile of drift can only be rounded to one of eight
# directions, six tiles to far more. At C<rotate> 0 nothing is approximated.
sub _watermark_slide
{
    my ( $ctx, $p, $xperiod, $yperiod ) = @_;

    my $compass = $COMPASS{ lc $p->{ direction } } or return ( 0, 0 );

    my ( $dx, $dy ) = @$compass;

    # Normalised, so a diagonal travels as fast as a cardinal rather than the
    # square root of two times faster.
    my $length = sqrt( $dx**2 + $dy**2 ) || 1;
    $dx /= $length;
    $dy /= $length;

    # Undoing the rotation the layer has not had applied yet.
    my $rad = -$p->{ rotate } * $PI / 180;
    my $lx  = $dx * cos( $rad ) - $dy * sin( $rad );
    my $ly  = $dx * sin( $rad ) + $dy * cos( $rad );

    # In tiles, then rounded to whole ones.
    my $tiles = $p->{ drift } || 0;
    my $mx    = _round( $tiles * $lx );
    my $my    = _round( $tiles * $ly * $xperiod / $yperiod );

    # Rounding both to nothing would take a drift somebody asked for and make
    # it stand still, which reads as a broken parameter. The larger component
    # gets the one tile instead.
    if ( $tiles && !$mx && !$my )
    {
        if   ( abs $lx >= abs $ly ) { $mx = $lx < 0 ? -1 : 1 }
        else                        { $my = $ly < 0 ? -1 : 1 }
    }

    my $phase = $ctx->phase;

    return (
        _wrap( $mx * $xperiod * $phase, $xperiod ),
        _wrap( $my * $yperiod * $phase, $yperiod )
    );
}

sub _round { return int( $_[ 0 ] + ( $_[ 0 ] < 0 ? -0.5 : 0.5 ) ) }

# Into one tile. Sliding by six tiles and by one look identical, so there is
# no reason to draw the other five off the edge of the canvas.
sub _wrap
{
    my ( $value, $period ) = @_;

    return 0 unless $period;

    $value -= $period * int( $value / $period );
    $value += $period if $value < 0;

    return $value;
}

# ---------------------------------------------------------------------------

sub _annotate
{
    my ( $ctx, %a ) = @_;

    my $img  = $ctx->image;
    my $text = Encode::encode( 'UTF-8', $a{ string } );

    # Fully opaque unless the caller asked otherwise; an explicit 0 must be
    # honoured rather than treated as "unset".
    my $opacity = 1;
    if ( defined $a{ opacity } )
    {
        $opacity = $a{ opacity };
    }

    my %args = (
        text      => $text,
        font      => $a{ font },
        pointsize => $a{ size },
        fill      => $a{ color },
        gravity   => $a{ gravity } // 'NorthWest',
        x         => int( $a{ x } // 0 ),
        y         => int( $a{ y } // 0 ),
        encoding  => 'UTF-8',
        antialias => 'true',
    );
    $args{ rotate } = $a{ rotate } if $a{ rotate };

    if ( $opacity < 1 )
    {
        # Annotate has no opacity control, so draw onto a transparent layer,
        # fade it, and composite.
        require Image::Magick;
        my ( $w, $h ) = $ctx->dims;

        my $layer = Image::Magick->new( size => "${w}x${h}" );
        $layer->Read( 'xc:transparent' );
        GlitchVape::Magick::check( $layer->Annotate( %args ),
            "text: could not render with font '$a{font}'" );

        $layer->Evaluate(
            operator => 'Multiply',
            value    => $opacity,
            channel  => 'Alpha',
        );
        $img->Composite( image => $layer->[ 0 ], compose => 'Over' );
        return;
    }

    GlitchVape::Magick::check( $img->Annotate( %args ),
        "text: could not render with font '$a{font}'" );
    return;
}

1;
