package GlitchVape::Effect::Overlay;

use strict;
use warnings;
use utf8;

use Encode ();

use GlitchVape::Magick   ();
use GlitchVape::Registry ();
use GlitchVape::Fonts    ();
use GlitchVape::Palette  ();

our $VERSION = '0.01';

=head1 NAME

GlitchVape::Effect::Overlay - text, camcorder furniture and drawn graphics

=head1 DESCRIPTION

Everything drawn on top of the picture rather than done to it. These run last,
because on-screen display is generated by the camera or the player and is not
subject to the tape damage the picture went through -- which is exactly why
crisp white C<REC> text over a degraded image reads as authentic.

=cut

my $R  = 'GlitchVape::Registry';
my $PI = 3.14159265358979;

# Stock phrases. Mostly the words the genre actually uses, which are not always
# the words a translation would pick: 蒸気波 is a literal calque of "vapor
# wave" that exists because of the genre, not before it.
my @PHRASES = (
    'ヴェイパーウェイブ',    # vaporwave
    '蒸気波',          # vapor wave (calque)
    '美的',           # aesthetic
    '未来',           # future
    '夢',            # dream
    '無限',           # infinity
    '電脳',           # cyber
    '東京',           # Tokyo
    '音楽',           # music
    '現実を超えて',       # beyond reality
    '記憶',           # memory
    '孤独',           # solitude
    '夜',            # night
    '水',            # water
    '新世紀',          # new century
);

# ---------------------------------------------------------------------------

$R->register(
    name    => 'text',
    title   => 'Text',
    stage   => 'overlay',
    summary => 'Draw text over the image',
    doc     => <<'DOC',
Renders a string, defaulting to a randomly chosen Japanese phrase from a built
in list. The C<shadow> offset draws the same text in a contrasting colour
behind the main copy, which is what stops light text disappearing into a light
background.
DOC
    params => {
        string => {
            default => '',
            type    => 'str',
            doc     => 'Text to draw; empty picks a random Japanese phrase',
        },
        font => {
            default => 'cjk',
            type    => 'str',
            doc     => 'Font role (cjk, vcr, pixel, mono, sans) or a font path',
        },
        size => {
            default => 12,
            type    => 'num',
            min     => 0.5,
            max     => 100,
            doc     => 'Height of the type as a percentage of the image height',
        },
        gravity => {
            default => 'Center',
            type    => 'enum',
            values  => [
                qw(NorthWest North NorthEast West Center East
                    SouthWest South SouthEast)
            ],
            doc => 'Where the text sits',
        },
        color => {
            default => '#FFFFFF',
            type    => 'str',
            doc     => 'Fill colour',
        },
        shadow => {
            default => '#FF00AA',
            type    => 'str',
            doc     => 'Offset copy drawn behind; empty to disable',
        },
        shadow_offset => {
            default => 4,
            type    => 'num',
            min     => -100,
            max     =>  100,
            doc     => 'Shadow displacement in pixels',
        },
        opacity => {
            default => 0.9,
            type    => 'num',
            min     => 0,
            max     => 1,
            doc     => 'Text opacity',
        },
        x => {
            default => 0.04,
            type    => 'num',
            min     => -1,
            max     =>  1,
            doc     => 'Horizontal inset as a fraction of width',
        },
        y => {
            default => 0.04,
            type    => 'num',
            min     => -1,
            max     =>  1,
            doc     => 'Vertical inset as a fraction of height',
        },
        rotate => {
            default => 0,
            type    => 'num',
            min     => -180,
            max     =>  180,
            doc     => 'Rotation in degrees',
        },
        spacing => {
            default => 0,
            type    => 'num',
            min     => -50,
            max     => 200,
            doc     => 'Extra letter spacing; wide tracking is a genre staple',
        },
    },
    apply => \&_text,
);

sub _text
{
    my ( $ctx, $p ) = @_;
    return if $p->{ opacity } <= 0;

    my $rng = $ctx->rng_for( 'text' );

    # An empty string means "surprise me", which is how the presets get
    # varied Japanese text without naming a phrase in every one.
    my $str = $p->{ string };
    if ( !length $str )
    {
        $str = $rng->pick( @PHRASES );
    }

    # Wide tracking is done by hand because ImageMagick has no letter-spacing
    # control; inserting thin spaces is the usual workaround.
    if ( $p->{ spacing } > 0 )
    {
        my $gap = ' ' x ( int( $p->{ spacing } / 8 ) || 1 );
        $str = join $gap, split //, $str;
    }

    my ( $w, $h ) = $ctx->dims;
    my $font =
        GlitchVape::Fonts::resolve_or_die( $p->{ font }, "effect 'text'" );
    my $size = int( $h * $p->{ size } / 100 ) || 8;

    my $dx = int( $w * $p->{ x } );
    my $dy = int( $h * $p->{ y } );

    my %common = (
        string  => $str,
        font    => $font,
        size    => $size,
        gravity => $p->{ gravity },
        opacity => $p->{ opacity },
        rotate  => $p->{ rotate },
    );

    if ( length $p->{ shadow } && $p->{ shadow_offset } )
    {
        _annotate(
            $ctx, %common,
            color => $p->{ shadow },
            x     => $dx + $p->{ shadow_offset },
            y     => $dy + $p->{ shadow_offset },
        );
    }

    _annotate( $ctx, %common, color => $p->{ color }, x => $dx, y => $dy );
    return;
}

# ---------------------------------------------------------------------------

$R->register(
    name    => 'osd',
    title   => 'Camcorder OSD',
    stage   => 'overlay',
    summary => 'Camcorder on-screen display: REC, timestamp, tape mode',
    doc     => <<'DOC',
The furniture a 1990s camcorder burned into the picture. Defaults place a
blinking record indicator top-left and a date/time bottom-right, which is where
most consumer models actually put them.

The date defaults to a random day in the 1990s, since a real timestamp on a
vaporwave image is an anachronism that undercuts the whole effect.
DOC
    params => {
        rec => {
            default => 1,
            type    => 'bool',
            doc     => 'Draw the record indicator',
        },
        rec_text => {
            default => 'REC',
            type    => 'str',
            doc     => 'Label beside the record dot',
        },
        timestamp => {
            default => 1,
            type    => 'bool',
            doc     => 'Draw the date and time',
        },
        date => {
            default => '',
            type    => 'str',
            doc     => 'Literal date string; empty generates a 1990s date',
        },
        time => {
            default => '',
            type    => 'str',
            doc     => 'Literal time string; empty generates one',
        },
        mode => {
            default => 'SP',
            type    => 'str',
            doc     => 'Tape speed indicator; empty to omit',
        },
        play => {
            default => 0,
            type    => 'bool',
            doc     => 'Draw a PLAY transport indicator',
        },
        font => {
            default => 'vcr',
            type    => 'str',
            doc     => 'Font role or path',
        },
        size => {
            default => 4.5,
            type    => 'num',
            min     => 0.5,
            max     => 50,
            doc     => 'Height of the type as a percentage of the image height',
        },
        color => {
            default => '#FFFFFF',
            type    => 'str',
            doc     => 'Text colour',
        },
        margin => {
            default => 0.045,
            type    => 'num',
            min     => 0,
            max     => 0.5,
            doc     => 'Inset from the edges',
        },
    },
    apply => \&_osd,
);

sub _osd
{
    my ( $ctx, $p ) = @_;

    my ( $w, $h ) = $ctx->dims;
    my $rng = $ctx->rng_for( 'osd' );
    my $font =
        GlitchVape::Fonts::resolve_or_die( $p->{ font }, "effect 'osd'" );
    my $size = int( $h * $p->{ size } / 100 ) || 10;

    my $mx = int( $w * $p->{ margin } );
    my $my = int( $h * $p->{ margin } );

    # Every piece of on-screen display shares its face, size and colour; only
    # the string and corner change.
    my %osd = ( font => $font, size => $size, color => $p->{ color } );

    if ( $p->{ rec } )
    {
        # The dot blinks across an animation, as the real indicator does.
        # The record dot blinks across an animation, as the real indicator
        # does, and is simply always lit on a still.
        my $on = 1;
        if ( $ctx->frames > 1 )
        {
            $on = 0;
            if ( $ctx->phase < 0.6 )
            {
                $on = 1;
            }
        }

        if ( $on )
        {
            my $r  = int( $size * 0.32 );
            my $cx = $mx + $r;
            my $cy = $my + int( $size * 0.42 );
            $ctx->magick( '-fill', '#FF2020', '-stroke', 'none', '-draw',
                sprintf( 'circle %d,%d %d,%d', $cx, $cy, $cx + $r, $cy ),
            );
        }

        _annotate(
            $ctx, %osd,
            string  => $p->{ rec_text },
            gravity => 'NorthWest',
            x       => $mx + int( $size * 0.95 ),
            y       => $my,
        );
    }

    if ( $p->{ play } )
    {
        my $y   = $my + int( $size * 1.6 );
        my $tri = int( $size * 0.45 );
        my $x0  = $mx;
        $ctx->magick(
            '-fill',
            $p->{ color },
            '-stroke',
            'none', '-draw',
            sprintf(
                'polygon %d,%d %d,%d %d,%d',
                $x0, $y, $x0,
                $y + $tri * 2,
                $x0 + $tri * 1.7,
                $y + $tri
            ),
        );
        _annotate(
            $ctx, %osd,
            string  => 'PLAY',
            gravity => 'NorthWest',
            x       => $mx + int( $size * 0.95 ),
            y       => $y - int( $size * 0.15 ),
        );
    }

    if ( $p->{ timestamp } )
    {
        # A literal date wins; otherwise invent a plausible 1990s one, since
        # a real present-day timestamp undercuts the whole conceit.
        my $date = $p->{ date };
        if ( !length $date )
        {
            $date = _fake_date( $rng );
        }

        my $time = $p->{ time };
        if ( !length $time )
        {
            $time = _fake_time( $rng );
        }

        _annotate(
            $ctx, %osd,
            string  => $time,
            gravity => 'SouthEast',
            x       => $mx,
            y       => $my,
        );
        _annotate(
            $ctx, %osd,
            string  => $date,
            gravity => 'SouthEast',
            x       => $mx,
            y       => $my + int( $size * 1.25 ),
        );
    }

    if ( length $p->{ mode } )
    {
        _annotate(
            $ctx, %osd,
            string  => $p->{ mode },
            gravity => 'NorthEast',
            x       => $mx,
            y       => $my,
        );
    }
    return;
}

my @MONTH = qw(JAN FEB MAR APR MAY JUN JUL AUG SEP OCT NOV DEC);

sub _fake_date
{
    my ( $rng ) = @_;
    return sprintf '%s %02d %d',
        $rng->pick( @MONTH ),
        $rng->int_between( 1,    28 ),
        $rng->int_between( 1990, 1999 );
}

sub _fake_time
{
    my ( $rng ) = @_;

    # 12-hour with a leading space, the way the cheap OSD chips rendered it.
    my $meridiem = 'PM';
    if ( $rng->chance( 0.5 ) )
    {
        $meridiem = 'AM';
    }

    return sprintf '%s %2d:%02d',
        $meridiem,
        $rng->int_between( 1, 12 ),
        $rng->int_between( 0, 59 );
}

# ---------------------------------------------------------------------------

$R->register(
    name    => 'grid',
    title   => 'Perspective Grid',
    stage   => 'overlay',
    summary => 'Retro perspective grid and sun',
    doc     => <<'DOC',
The synthwave horizon: a ground plane receding to a vanishing point, optionally
with a banded sun sitting on it. Horizontal line spacing follows a power curve
so the lines bunch up towards the horizon the way perspective actually makes
them, rather than being evenly spaced.
DOC
    params => {
        horizon => {
            default => 0.62,
            type    => 'num',
            min     => 0.05,
            max     => 0.95,
            doc     => 'Horizon height as a fraction from the top',
        },
        lines_h => {
            default => 14,
            type    => 'int',
            min     => 0,
            max     => 200,
            doc     => 'Number of horizontal lines',
        },
        lines_v => {
            default => 22,
            type    => 'int',
            min     => 0,
            max     => 200,
            doc     => 'Number of converging vertical lines',
        },
        color => {
            default => '#FF00AA',
            type    => 'str',
            doc     => 'Grid line colour',
        },
        width => {
            default => 2,
            type    => 'num',
            min     => 0.2,
            max     => 20,
            doc     => 'Line width in pixels',
        },
        opacity => {
            default => 0.75,
            type    => 'num',
            min     => 0,
            max     => 1,
            doc     => 'Grid opacity',
        },
        perspective => {
            default => 2.2,
            type    => 'num',
            min     => 1,
            max     => 8,
            doc => 'How hard the horizontal lines bunch towards the horizon',
        },
        drift => {
            default => 0,
            type    => 'num',
            min     => -64,
            max     =>  64,
            doc     => 'Grid lines travelled per loop; negative recedes',
        },
        sun => {
            default => 1,
            type    => 'bool',
            doc     => 'Draw the banded sun',
        },
        sun_size => {
            default => 0.22,
            type    => 'num',
            min     => 0.02,
            max     => 1,
            doc     => 'Sun diameter as a fraction of image width',
        },
        sun_colors => {
            default => '#FFE261,#FF3864',
            type    => 'str',
            doc     => 'Top and bottom colours of the sun gradient',
        },
        sun_bands => {
            default => 7,
            type    => 'int',
            min     => 0,
            max     => 60,
            doc     => 'Slots cut across the lower half of the sun',
        },
    },
    apply => \&_grid,
);

sub _grid
{
    my ( $ctx, $p ) = @_;
    return if $p->{ opacity } <= 0;
    require Image::Magick;

    my ( $w, $h ) = $ctx->dims;
    my $hy = int( $h * $p->{ horizon } );
    my $cx = int( $w / 2 );

    my $layer = Image::Magick->new( size => "${w}x${h}" );
    GlitchVape::Magick::check( $layer->Read( 'xc:transparent' ),
        "grid: could not create layer" );

    _draw_sun( $layer, $p, $w, $h ) if $p->{ sun };

    my @draw;

    # Horizontal lines: t^perspective spaces them tightly at the horizon and
    # widely at the bottom of the frame.
    #
    # Drift moves them along that curve rather than down the screen, which is
    # the whole trick: a line travelling at constant speed in t accelerates
    # towards the viewer exactly as the spacing widens, so the plane reads as
    # ground going past instead of as stripes sliding. One line spacing is the
    # repeat, so travel() snaps to whole lines and the loop closes with a line
    # sitting where its neighbour started.
    #
    # Only these move. The vertical lines converge on the vanishing point and
    # are the same set of rays whatever the ground is doing; scrolling them
    # would swing the whole plane sideways.
    my $shift = $ctx->travel( $p->{ drift }, 1 );
    my $extra = int( abs $p->{ drift } ) + 1;

    for my $i ( 1 - $extra .. $p->{ lines_h } + $extra )
    {
        my $t = ( $i + $shift ) / $p->{ lines_h };

        # Off the top past the horizon, or off the bottom of the frame.
        next if $t <= 0 || $t > 1;

        my $y = $hy + ( $h - $hy ) * ( $t**$p->{ perspective } );
        push @draw, sprintf( 'line 0,%.1f %d,%.1f', $y, $w, $y );
    }

    # Vertical lines all converge on the vanishing point. Spreading their
    # bottom ends well past the frame edges keeps the outermost ones steep
    # enough to look like part of the same plane.
    if ( $p->{ lines_v } )
    {
        my $spread = $w * 2.5;
        for my $i ( 0 .. $p->{ lines_v } )
        {
            my $t = $i / $p->{ lines_v };
            my $x = $cx - $spread / 2 + $spread * $t;
            push @draw, sprintf( 'line %d,%d %.1f,%d', $cx, $hy, $x, $h );
        }
    }

    if ( @draw )
    {
        for my $d ( @draw )
        {
            my ( $prim, @pts ) = split ' ', $d;
            $layer->Draw(
                primitive   => $prim,
                points      => join( ' ', @pts ),
                stroke      => $p->{ color },
                strokewidth => $p->{ width },
                fill        => 'none',
                antialias   => 'true',
            );
        }
    }

    if ( $p->{ opacity } < 1 )
    {
        $layer->Evaluate(
            operator => 'Multiply',
            value    => $p->{ opacity },
            channel  => 'Alpha',
        );
    }

    $ctx->image->Composite( image => $layer->[ 0 ], compose => 'Over' );
    return;
}

sub _draw_sun
{
    my ( $layer, $p, $w, $h ) = @_;
    require Image::Magick;

    # Horizon and centre are derived rather than passed in: they are a
    # function of the geometry the caller already hands over.
    my $hy = int( $h * $p->{ horizon } );
    my $cx = int( $w / 2 );

    my $d = int( $w * $p->{ sun_size } );
    return if $d < 4;
    my $r = int( $d / 2 );

    my @cols = split /\s*,\s*/, $p->{ sun_colors };
    push @cols, $cols[ 0 ] if @cols < 2;

    # Build the sun as its own square image: a vertical gradient masked by a
    # circle. Drawing a gradient-filled circle directly is not something
    # ImageMagick's draw primitives can do.
    my $disc = Image::Magick->new( size => "${d}x${d}" );
    $disc->Read( "gradient:$cols[0]-$cols[1]" );

    my $mask = Image::Magick->new( size => "${d}x${d}" );
    $mask->Read( 'xc:black' );
    $mask->Draw(
        primitive => 'circle',
        points    => sprintf( '%d,%d %d,%d', $r, $r, $r, 0 ),
        fill      => 'white',
        stroke    => 'none',
    );

    # Slots across the lower half, widening towards the bottom.
    if ( $p->{ sun_bands } )
    {
        for my $i ( 1 .. $p->{ sun_bands } )
        {
            my $t  = $i / ( $p->{ sun_bands } + 1 );
            my $y  = $r + ( $d - $r ) * ( $t**1.4 );
            my $th = 1 + $t * $r * 0.16;
            $mask->Draw(
                primitive   => 'line',
                points      => sprintf( '0,%.1f %d,%.1f', $y, $d, $y ),
                stroke      => 'black',
                strokewidth => $th,
                fill        => 'none',
            );
        }
    }

    # The mask carries the shape as black and white pixels, so its intensity
    # has to be moved into its alpha channel before the composite. IM6's
    # CopyOpacity fell back to intensity when the source had no alpha; IM7
    # aliases CopyOpacity to CopyAlpha, which copies the alpha channel and
    # nothing else -- and `xc:black` arrives with a fully opaque one. Without
    # the copy the sun composites as an opaque square with no slots in it.
    $mask->Set( alpha => 'copy' );

    $disc->Set( alpha => 'on' );
    $disc->Composite( image => $mask->[ 0 ], compose => 'CopyAlpha' );

    my $x = $cx - $r;
    my $y = $hy - int( $r * 1.15 );

    $layer->Composite(
        image   => $disc->[ 0 ],
        compose => 'Over',
        x       => $x,
        y       => $y
    );
    return;
}

# ---------------------------------------------------------------------------

$R->register(
    name    => 'letterbox',
    title   => 'Letterbox & Border',
    stage   => 'framing',
    summary => 'Black bars, or a border around the frame',
    doc     => <<'DOC',
Crops to a target aspect ratio with bars, or draws a plain inset border. Bars
sell the "recorded off a broadcast" idea; a border reads more like a photo
print.
DOC
    params => {
        ratio => {
            default => '16:9',
            type    => 'str',
            suggest => 'ratio',
            doc     => 'Target aspect, e.g. "16:9" or "4:3"; empty to skip',
        },
        color => {
            default => 'black',
            type    => 'str',
            doc     => 'Bar or border colour',
        },
        border => {
            default => 0,
            type    => 'num',
            min     => 0,
            max     => 0.5,
            doc     => 'Uniform border as a fraction of the shorter side',
        },
    },
    apply => \&_letterbox,
);

sub _letterbox
{
    my ( $ctx, $p ) = @_;

    if ( length $p->{ ratio } )
    {
        my ( $rw, $rh ) =
            $p->{ ratio } =~
            m{^\s*(\d+(?:\.\d+)?)\s*[:x/]\s*(\d+(?:\.\d+)?)\s*$}
            or die
            "letterbox: ratio must look like '16:9', got '$p->{ratio}'\n";

        my ( $w, $h ) = $ctx->dims;
        my $target = $rw / $rh;
        my $cur    = $w / $h;

        my ( $nw, $nh ) =
            $cur > $target
            ? ( $w, int( $w / $target ) )
            : ( int( $h * $target ), $h );

        $ctx->magick(
            '-background', $p->{ color }, '-gravity', 'Center',
            '-extent',     "${nw}x${nh}",
        );
    }

    if ( $p->{ border } > 0 )
    {
        my ( $w, $h ) = $ctx->dims;

        # Border width is a fraction of the shorter side, so a panorama does
        # not get an absurdly thick frame on its short edge.
        my $shorter = $h;
        if ( $w < $h )
        {
            $shorter = $w;
        }

        my $b = int( $shorter * $p->{ border } );
        $ctx->magick( '-bordercolor', $p->{ color }, '-border', $b ) if $b > 0;
    }
    return;
}

# ---------------------------------------------------------------------------

$R->register(
    name    => 'watermark',
    title   => 'Tiled Watermark',
    stage   => 'overlay',
    summary => 'Tiled repeating text across the whole frame',
    doc     => <<'DOC',
Repeats a string in a low-contrast grid over the image, in the manner of a
stock-photo proof or a corrupted screensaver.

C<drift> slides the whole tiling along the text's own reading direction, so
with C<rotate> set the motion comes out diagonal and the thing reads as the
screensaver it is imitating. This is the effect that animates most cleanly of
any of them, and for a reason worth knowing: a tiled pattern has an exact
period, so moving it a whole number of tiles per loop returns it to itself
with nothing to hide and no speed at which it goes wrong. Everything else that
drifts has to snap or rock to close its loop; this one simply closes.
DOC
    params => {
        string => {
            default => '美的',
            type    => 'str',
            doc     => 'Text to repeat',
        },
        font => {
            default => 'cjk',
            type    => 'str',
            doc     => 'Font role or path',
        },
        size => {
            default => 5,
            type    => 'num',
            min     => 0.5,
            max     => 100,
            doc     => 'Height of the type as a percentage of the image height',
        },
        color => {
            default => '#FFFFFF',
            type    => 'str',
            doc     => 'Text colour',
        },
        opacity => {
            default => 0.12,
            type    => 'num',
            min     => 0,
            max     => 1,
            doc     => 'Overall opacity',
        },
        rotate => {
            default => -30,
            type    => 'num',
            min     => -180,
            max     =>  180,
            doc     => 'Rotation of the tiled text',
        },
        spacing => {
            default => 2.2,
            type    => 'num',
            min     => 1,
            max     => 12,
            doc     => 'Gap between repetitions, in multiples of text size',
        },
        drift => {
            default => 0,
            type    => 'num',
            min     => -32,
            max     =>  32,
            doc     => 'Tiles the pattern slides per loop; negative reverses',
        },
    },
    apply => \&_watermark,
);

sub _watermark
{
    my ( $ctx, $p ) = @_;
    return if $p->{ opacity } <= 0;
    require Image::Magick;

    my ( $w, $h ) = $ctx->dims;
    my $font =
        GlitchVape::Fonts::resolve_or_die( $p->{ font }, "effect 'watermark'" );
    my $size = int( $h * $p->{ size } / 100 ) || 8;

    # Rotating the finished layer means building it on an oversized canvas so
    # the corners are still covered afterwards.
    my $diag = int( sqrt( $w * $w + $h * $h ) ) + $size * 4;

    my $layer = Image::Magick->new( size => "${diag}x${diag}" );
    $layer->Read( 'xc:transparent' );

    my $step = int( $size * $p->{ spacing } ) || $size;
    my $text = Encode::encode( 'UTF-8', $p->{ string } );

    # One tile across. The inner loop below lays repetitions down at this
    # interval, so it is also the distance the pattern has to slide to look
    # untouched -- which is what makes the scroll loop exactly.
    my $period = $step * 2;

    # Wrapped into one tile: sliding by six tiles and by one look the same, so
    # there is no reason to draw the other five off the edge of the canvas.
    my $slide = $ctx->travel( $p->{ drift }, 1 ) * $period;
    $slide -= $period * int( $slide / $period );

    my $row = 0;
    for ( my $y = 0 ; $y < $diag ; $y += $step )
    {
        # Offset every other row by half a step so the tiling reads as a
        # scatter rather than as columns.
        my $stagger = $row++ % 2 ? int( $step / 2 ) : 0;

        # A tile's margin either side, so the one sliding in at the left edge
        # is already drawn when it gets there.
        for ( my $x = -$period ; $x < $diag + $period ; $x += $period )
        {
            $layer->Annotate(
                text      => $text,
                font      => $font,
                pointsize => $size,
                fill      => $p->{ color },
                x         => $x + $stagger + $slide,
                y         => $y,
                gravity   => 'NorthWest',
                encoding  => 'UTF-8',
                antialias => 'true',
            );
        }
    }

    $layer->Rotate( degrees => $p->{ rotate }, background => 'transparent' );
    $layer->Set( gravity => 'Center' );
    $layer->Crop( geometry => "${w}x${h}+0+0", gravity => 'Center' );
    $layer->Set( page => '0x0+0+0' );

    $layer->Evaluate(
        operator => 'Multiply',
        value    => $p->{ opacity },
        channel  => 'Alpha',
    );

    $ctx->image->Composite(
        image   => $layer->[ 0 ],
        compose => 'Over',
        gravity => 'Center',
    );
    return;
}

# ---------------------------------------------------------------------------

sub _annotate
{
    my ( $ctx, %a ) = @_;

    my $img  = $ctx->image;
    my $text = Encode::encode( 'UTF-8', $a{ string } );

    # Fully opaque unless the caller asked otherwise; an explicit 0 must be
    # honoured rather than treated as "unset".
    my $opacity = 1;
    if ( defined $a{ opacity } )
    {
        $opacity = $a{ opacity };
    }

    my %args = (
        text      => $text,
        font      => $a{ font },
        pointsize => $a{ size },
        fill      => $a{ color },
        gravity   => $a{ gravity } // 'NorthWest',
        x         => int( $a{ x } // 0 ),
        y         => int( $a{ y } // 0 ),
        encoding  => 'UTF-8',
        antialias => 'true',
    );
    $args{ rotate } = $a{ rotate } if $a{ rotate };

    if ( $opacity < 1 )
    {
        # Annotate has no opacity control, so draw onto a transparent layer,
        # fade it, and composite.
        require Image::Magick;
        my ( $w, $h ) = $ctx->dims;

        my $layer = Image::Magick->new( size => "${w}x${h}" );
        $layer->Read( 'xc:transparent' );
        GlitchVape::Magick::check( $layer->Annotate( %args ),
            "text: could not render with font '$a{font}'" );

        $layer->Evaluate(
            operator => 'Multiply',
            value    => $opacity,
            channel  => 'Alpha',
        );
        $img->Composite( image => $layer->[ 0 ], compose => 'Over' );
        return;
    }

    GlitchVape::Magick::check( $img->Annotate( %args ),
        "text: could not render with font '$a{font}'" );
    return;
}

1;
